<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WinSonic.Core\WinSonic.Core.csproj" />
      <ProjectReference Include="..\WinSonic.Data\WinSonic.Data.csproj" />
      <ProjectReference Include="..\WinSonic.Subsonic.Client\src\WinSonic.Subsonic.Client\WinSonic.Subsonic.Client.csproj" />
      <ProjectReference Include="..\WinSonic.Subsonic.Helpers\WinSonic.Subsonic.Helpers.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Album\" />
      <Folder Include="History\" />
    </ItemGroup>

</Project>
