/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using WinSonic.Subsonic.Client.Client;
using WinSonic.Subsonic.Client.Model;

namespace WinSonic.Subsonic.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITranscodingApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Transcode Decision
        /// </summary>
        /// <remarks>
        /// Returns a transcode decision for a given media file.
        /// </remarks>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="clientInfo"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetTranscodeDecision200Response</returns>
        GetTranscodeDecision200Response GetTranscodeDecision(string mediaId, string mediaType, ClientInfo clientInfo, int operationIndex = 0);

        /// <summary>
        /// Get Transcode Decision
        /// </summary>
        /// <remarks>
        /// Returns a transcode decision for a given media file.
        /// </remarks>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="clientInfo"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetTranscodeDecision200Response</returns>
        ApiResponse<GetTranscodeDecision200Response> GetTranscodeDecisionWithHttpInfo(string mediaId, string mediaType, ClientInfo clientInfo, int operationIndex = 0);
        /// <summary>
        /// Get Transcoded Stream
        /// </summary>
        /// <remarks>
        /// Returns a transcoded media stream. Clients should not try to reconstruct the &#x60;transcodeParams&#x60;. Instead, they must use the &#x60;transcodeParams&#x60; provided in the response of the &#x60;getTranscodeDecision&#x60; endpoint.
        /// </remarks>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="transcodeParams">Server-specific transcoding parameters. This should be obtained from the &#x60;getTranscodeDecision&#x60; endpoint.</param>
        /// <param name="offset">The time offset in seconds from which to start transcoding. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetTranscodeStream(string mediaId, string mediaType, string transcodeParams, int? offset = default, int operationIndex = 0);

        /// <summary>
        /// Get Transcoded Stream
        /// </summary>
        /// <remarks>
        /// Returns a transcoded media stream. Clients should not try to reconstruct the &#x60;transcodeParams&#x60;. Instead, they must use the &#x60;transcodeParams&#x60; provided in the response of the &#x60;getTranscodeDecision&#x60; endpoint.
        /// </remarks>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="transcodeParams">Server-specific transcoding parameters. This should be obtained from the &#x60;getTranscodeDecision&#x60; endpoint.</param>
        /// <param name="offset">The time offset in seconds from which to start transcoding. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetTranscodeStreamWithHttpInfo(string mediaId, string mediaType, string transcodeParams, int? offset = default, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITranscodingApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Transcode Decision
        /// </summary>
        /// <remarks>
        /// Returns a transcode decision for a given media file.
        /// </remarks>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="clientInfo"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetTranscodeDecision200Response</returns>
        System.Threading.Tasks.Task<GetTranscodeDecision200Response> GetTranscodeDecisionAsync(string mediaId, string mediaType, ClientInfo clientInfo, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Transcode Decision
        /// </summary>
        /// <remarks>
        /// Returns a transcode decision for a given media file.
        /// </remarks>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="clientInfo"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetTranscodeDecision200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetTranscodeDecision200Response>> GetTranscodeDecisionWithHttpInfoAsync(string mediaId, string mediaType, ClientInfo clientInfo, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Transcoded Stream
        /// </summary>
        /// <remarks>
        /// Returns a transcoded media stream. Clients should not try to reconstruct the &#x60;transcodeParams&#x60;. Instead, they must use the &#x60;transcodeParams&#x60; provided in the response of the &#x60;getTranscodeDecision&#x60; endpoint.
        /// </remarks>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="transcodeParams">Server-specific transcoding parameters. This should be obtained from the &#x60;getTranscodeDecision&#x60; endpoint.</param>
        /// <param name="offset">The time offset in seconds from which to start transcoding. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetTranscodeStreamAsync(string mediaId, string mediaType, string transcodeParams, int? offset = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Transcoded Stream
        /// </summary>
        /// <remarks>
        /// Returns a transcoded media stream. Clients should not try to reconstruct the &#x60;transcodeParams&#x60;. Instead, they must use the &#x60;transcodeParams&#x60; provided in the response of the &#x60;getTranscodeDecision&#x60; endpoint.
        /// </remarks>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="transcodeParams">Server-specific transcoding parameters. This should be obtained from the &#x60;getTranscodeDecision&#x60; endpoint.</param>
        /// <param name="offset">The time offset in seconds from which to start transcoding. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetTranscodeStreamWithHttpInfoAsync(string mediaId, string mediaType, string transcodeParams, int? offset = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITranscodingApi : ITranscodingApiSync, ITranscodingApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TranscodingApi : ITranscodingApi
    {
        private WinSonic.Subsonic.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TranscodingApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TranscodingApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranscodingApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TranscodingApi(string basePath)
        {
            this.Configuration = WinSonic.Subsonic.Client.Client.Configuration.MergeConfigurations(
                WinSonic.Subsonic.Client.Client.GlobalConfiguration.Instance,
                new WinSonic.Subsonic.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new WinSonic.Subsonic.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new WinSonic.Subsonic.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = WinSonic.Subsonic.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranscodingApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TranscodingApi(WinSonic.Subsonic.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = WinSonic.Subsonic.Client.Client.Configuration.MergeConfigurations(
                WinSonic.Subsonic.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new WinSonic.Subsonic.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new WinSonic.Subsonic.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = WinSonic.Subsonic.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranscodingApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TranscodingApi(WinSonic.Subsonic.Client.Client.ISynchronousClient client, WinSonic.Subsonic.Client.Client.IAsynchronousClient asyncClient, WinSonic.Subsonic.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = WinSonic.Subsonic.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public WinSonic.Subsonic.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public WinSonic.Subsonic.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public WinSonic.Subsonic.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public WinSonic.Subsonic.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Transcode Decision Returns a transcode decision for a given media file.
        /// </summary>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="clientInfo"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetTranscodeDecision200Response</returns>
        public GetTranscodeDecision200Response GetTranscodeDecision(string mediaId, string mediaType, ClientInfo clientInfo, int operationIndex = 0)
        {
            WinSonic.Subsonic.Client.Client.ApiResponse<GetTranscodeDecision200Response> localVarResponse = GetTranscodeDecisionWithHttpInfo(mediaId, mediaType, clientInfo);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Transcode Decision Returns a transcode decision for a given media file.
        /// </summary>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="clientInfo"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetTranscodeDecision200Response</returns>
        public WinSonic.Subsonic.Client.Client.ApiResponse<GetTranscodeDecision200Response> GetTranscodeDecisionWithHttpInfo(string mediaId, string mediaType, ClientInfo clientInfo, int operationIndex = 0)
        {
            // verify the required parameter 'mediaId' is set
            if (mediaId == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'mediaId' when calling TranscodingApi->GetTranscodeDecision");
            }

            // verify the required parameter 'mediaType' is set
            if (mediaType == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'mediaType' when calling TranscodingApi->GetTranscodeDecision");
            }

            // verify the required parameter 'clientInfo' is set
            if (clientInfo == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'clientInfo' when calling TranscodingApi->GetTranscodeDecision");
            }

            WinSonic.Subsonic.Client.Client.RequestOptions localVarRequestOptions = new WinSonic.Subsonic.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = WinSonic.Subsonic.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = WinSonic.Subsonic.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "mediaId", mediaId));
            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "mediaType", mediaType));
            localVarRequestOptions.Data = clientInfo;

            localVarRequestOptions.Operation = "TranscodingApi.GetTranscodeDecision";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (legacyPassword) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("p")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "p", this.Configuration.GetApiKeyWithPrefix("p")));
            }
            // authentication (salt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("s")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "s", this.Configuration.GetApiKeyWithPrefix("s")));
            }
            // authentication (clientName) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("c")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "c", this.Configuration.GetApiKeyWithPrefix("c")));
            }
            // authentication (apiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }
            // authentication (format) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("f")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "f", this.Configuration.GetApiKeyWithPrefix("f")));
            }
            // authentication (protocolVersion) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("v")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "v", this.Configuration.GetApiKeyWithPrefix("v")));
            }
            // authentication (username) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("u")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "u", this.Configuration.GetApiKeyWithPrefix("u")));
            }
            // authentication (token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("t")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "t", this.Configuration.GetApiKeyWithPrefix("t")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<GetTranscodeDecision200Response>("/rest/getTranscodeDecision", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTranscodeDecision", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Transcode Decision Returns a transcode decision for a given media file.
        /// </summary>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="clientInfo"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetTranscodeDecision200Response</returns>
        public async System.Threading.Tasks.Task<GetTranscodeDecision200Response> GetTranscodeDecisionAsync(string mediaId, string mediaType, ClientInfo clientInfo, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            WinSonic.Subsonic.Client.Client.ApiResponse<GetTranscodeDecision200Response> localVarResponse = await GetTranscodeDecisionWithHttpInfoAsync(mediaId, mediaType, clientInfo, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Transcode Decision Returns a transcode decision for a given media file.
        /// </summary>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="clientInfo"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetTranscodeDecision200Response)</returns>
        public async System.Threading.Tasks.Task<WinSonic.Subsonic.Client.Client.ApiResponse<GetTranscodeDecision200Response>> GetTranscodeDecisionWithHttpInfoAsync(string mediaId, string mediaType, ClientInfo clientInfo, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'mediaId' is set
            if (mediaId == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'mediaId' when calling TranscodingApi->GetTranscodeDecision");
            }

            // verify the required parameter 'mediaType' is set
            if (mediaType == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'mediaType' when calling TranscodingApi->GetTranscodeDecision");
            }

            // verify the required parameter 'clientInfo' is set
            if (clientInfo == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'clientInfo' when calling TranscodingApi->GetTranscodeDecision");
            }


            WinSonic.Subsonic.Client.Client.RequestOptions localVarRequestOptions = new WinSonic.Subsonic.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = WinSonic.Subsonic.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = WinSonic.Subsonic.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "mediaId", mediaId));
            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "mediaType", mediaType));
            localVarRequestOptions.Data = clientInfo;

            localVarRequestOptions.Operation = "TranscodingApi.GetTranscodeDecision";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (legacyPassword) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("p")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "p", this.Configuration.GetApiKeyWithPrefix("p")));
            }
            // authentication (salt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("s")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "s", this.Configuration.GetApiKeyWithPrefix("s")));
            }
            // authentication (clientName) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("c")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "c", this.Configuration.GetApiKeyWithPrefix("c")));
            }
            // authentication (apiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }
            // authentication (format) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("f")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "f", this.Configuration.GetApiKeyWithPrefix("f")));
            }
            // authentication (protocolVersion) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("v")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "v", this.Configuration.GetApiKeyWithPrefix("v")));
            }
            // authentication (username) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("u")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "u", this.Configuration.GetApiKeyWithPrefix("u")));
            }
            // authentication (token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("t")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "t", this.Configuration.GetApiKeyWithPrefix("t")));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<GetTranscodeDecision200Response>("/rest/getTranscodeDecision", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTranscodeDecision", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Transcoded Stream Returns a transcoded media stream. Clients should not try to reconstruct the &#x60;transcodeParams&#x60;. Instead, they must use the &#x60;transcodeParams&#x60; provided in the response of the &#x60;getTranscodeDecision&#x60; endpoint.
        /// </summary>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="transcodeParams">Server-specific transcoding parameters. This should be obtained from the &#x60;getTranscodeDecision&#x60; endpoint.</param>
        /// <param name="offset">The time offset in seconds from which to start transcoding. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetTranscodeStream(string mediaId, string mediaType, string transcodeParams, int? offset = default, int operationIndex = 0)
        {
            WinSonic.Subsonic.Client.Client.ApiResponse<System.IO.Stream> localVarResponse = GetTranscodeStreamWithHttpInfo(mediaId, mediaType, transcodeParams, offset);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Transcoded Stream Returns a transcoded media stream. Clients should not try to reconstruct the &#x60;transcodeParams&#x60;. Instead, they must use the &#x60;transcodeParams&#x60; provided in the response of the &#x60;getTranscodeDecision&#x60; endpoint.
        /// </summary>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="transcodeParams">Server-specific transcoding parameters. This should be obtained from the &#x60;getTranscodeDecision&#x60; endpoint.</param>
        /// <param name="offset">The time offset in seconds from which to start transcoding. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public WinSonic.Subsonic.Client.Client.ApiResponse<System.IO.Stream> GetTranscodeStreamWithHttpInfo(string mediaId, string mediaType, string transcodeParams, int? offset = default, int operationIndex = 0)
        {
            // verify the required parameter 'mediaId' is set
            if (mediaId == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'mediaId' when calling TranscodingApi->GetTranscodeStream");
            }

            // verify the required parameter 'mediaType' is set
            if (mediaType == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'mediaType' when calling TranscodingApi->GetTranscodeStream");
            }

            // verify the required parameter 'transcodeParams' is set
            if (transcodeParams == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'transcodeParams' when calling TranscodingApi->GetTranscodeStream");
            }

            WinSonic.Subsonic.Client.Client.RequestOptions localVarRequestOptions = new WinSonic.Subsonic.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/octet-stream"
            };

            var localVarContentType = WinSonic.Subsonic.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = WinSonic.Subsonic.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "mediaId", mediaId));
            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "mediaType", mediaType));
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "transcodeParams", transcodeParams));

            localVarRequestOptions.Operation = "TranscodingApi.GetTranscodeStream";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (legacyPassword) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("p")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "p", this.Configuration.GetApiKeyWithPrefix("p")));
            }
            // authentication (salt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("s")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "s", this.Configuration.GetApiKeyWithPrefix("s")));
            }
            // authentication (clientName) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("c")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "c", this.Configuration.GetApiKeyWithPrefix("c")));
            }
            // authentication (apiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }
            // authentication (format) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("f")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "f", this.Configuration.GetApiKeyWithPrefix("f")));
            }
            // authentication (protocolVersion) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("v")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "v", this.Configuration.GetApiKeyWithPrefix("v")));
            }
            // authentication (username) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("u")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "u", this.Configuration.GetApiKeyWithPrefix("u")));
            }
            // authentication (token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("t")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "t", this.Configuration.GetApiKeyWithPrefix("t")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<System.IO.Stream>("/rest/getTranscodeStream", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTranscodeStream", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Transcoded Stream Returns a transcoded media stream. Clients should not try to reconstruct the &#x60;transcodeParams&#x60;. Instead, they must use the &#x60;transcodeParams&#x60; provided in the response of the &#x60;getTranscodeDecision&#x60; endpoint.
        /// </summary>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="transcodeParams">Server-specific transcoding parameters. This should be obtained from the &#x60;getTranscodeDecision&#x60; endpoint.</param>
        /// <param name="offset">The time offset in seconds from which to start transcoding. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetTranscodeStreamAsync(string mediaId, string mediaType, string transcodeParams, int? offset = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            WinSonic.Subsonic.Client.Client.ApiResponse<System.IO.Stream> localVarResponse = await GetTranscodeStreamWithHttpInfoAsync(mediaId, mediaType, transcodeParams, offset, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Transcoded Stream Returns a transcoded media stream. Clients should not try to reconstruct the &#x60;transcodeParams&#x60;. Instead, they must use the &#x60;transcodeParams&#x60; provided in the response of the &#x60;getTranscodeDecision&#x60; endpoint.
        /// </summary>
        /// <exception cref="WinSonic.Subsonic.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId">The ID of the media.</param>
        /// <param name="mediaType">The type of the media.</param>
        /// <param name="transcodeParams">Server-specific transcoding parameters. This should be obtained from the &#x60;getTranscodeDecision&#x60; endpoint.</param>
        /// <param name="offset">The time offset in seconds from which to start transcoding. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<WinSonic.Subsonic.Client.Client.ApiResponse<System.IO.Stream>> GetTranscodeStreamWithHttpInfoAsync(string mediaId, string mediaType, string transcodeParams, int? offset = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'mediaId' is set
            if (mediaId == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'mediaId' when calling TranscodingApi->GetTranscodeStream");
            }

            // verify the required parameter 'mediaType' is set
            if (mediaType == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'mediaType' when calling TranscodingApi->GetTranscodeStream");
            }

            // verify the required parameter 'transcodeParams' is set
            if (transcodeParams == null)
            {
                throw new WinSonic.Subsonic.Client.Client.ApiException(400, "Missing required parameter 'transcodeParams' when calling TranscodingApi->GetTranscodeStream");
            }


            WinSonic.Subsonic.Client.Client.RequestOptions localVarRequestOptions = new WinSonic.Subsonic.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/octet-stream"
            };

            var localVarContentType = WinSonic.Subsonic.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = WinSonic.Subsonic.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "mediaId", mediaId));
            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "mediaType", mediaType));
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "transcodeParams", transcodeParams));

            localVarRequestOptions.Operation = "TranscodingApi.GetTranscodeStream";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (legacyPassword) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("p")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "p", this.Configuration.GetApiKeyWithPrefix("p")));
            }
            // authentication (salt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("s")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "s", this.Configuration.GetApiKeyWithPrefix("s")));
            }
            // authentication (clientName) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("c")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "c", this.Configuration.GetApiKeyWithPrefix("c")));
            }
            // authentication (apiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }
            // authentication (format) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("f")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "f", this.Configuration.GetApiKeyWithPrefix("f")));
            }
            // authentication (protocolVersion) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("v")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "v", this.Configuration.GetApiKeyWithPrefix("v")));
            }
            // authentication (username) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("u")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "u", this.Configuration.GetApiKeyWithPrefix("u")));
            }
            // authentication (token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("t")))
            {
                localVarRequestOptions.QueryParameters.Add(WinSonic.Subsonic.Client.Client.ClientUtils.ParameterToMultiMap("", "t", this.Configuration.GetApiKeyWithPrefix("t")));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<System.IO.Stream>("/rest/getTranscodeStream", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTranscodeStream", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
