/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using WinSonic.Subsonic.Client.Client;
using WinSonic.Subsonic.Client.Api;
// uncomment below to import models
//using WinSonic.Subsonic.Client.Model;

namespace WinSonic.Subsonic.Client.Test.Api
{
    /// <summary>
    ///  Class for testing InternetRadioApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InternetRadioApiTests : IDisposable
    {
        private InternetRadioApi instance;

        public InternetRadioApiTests()
        {
            instance = new InternetRadioApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InternetRadioApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InternetRadioApi
            //Assert.IsType<InternetRadioApi>(instance);
        }

        /// <summary>
        /// Test CreateInternetRadioStation
        /// </summary>
        [Fact]
        public void CreateInternetRadioStationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string streamUrl = null;
            //string name = null;
            //string? homepageUrl = null;
            //var response = instance.CreateInternetRadioStation(streamUrl, name, homepageUrl);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test DeleteInternetRadioStation
        /// </summary>
        [Fact]
        public void DeleteInternetRadioStationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DeleteInternetRadioStation(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test GetInternetRadioStations
        /// </summary>
        [Fact]
        public void GetInternetRadioStationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetInternetRadioStations();
            //Assert.IsType<GetInternetRadioStationsResponse>(response);
        }

        /// <summary>
        /// Test PostCreateInternetRadioStation
        /// </summary>
        [Fact]
        public void PostCreateInternetRadioStationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string streamUrl = null;
            //string name = null;
            //string? homepageUrl = null;
            //var response = instance.PostCreateInternetRadioStation(streamUrl, name, homepageUrl);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test PostDeleteInternetRadioStation
        /// </summary>
        [Fact]
        public void PostDeleteInternetRadioStationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.PostDeleteInternetRadioStation(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test PostGetInternetRadioStations
        /// </summary>
        [Fact]
        public void PostGetInternetRadioStationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PostGetInternetRadioStations();
            //Assert.IsType<GetInternetRadioStationsResponse>(response);
        }

        /// <summary>
        /// Test PostUpdateInternetRadioStation
        /// </summary>
        [Fact]
        public void PostUpdateInternetRadioStationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string streamUrl = null;
            //string name = null;
            //string? homepageUrl = null;
            //var response = instance.PostUpdateInternetRadioStation(id, streamUrl, name, homepageUrl);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test UpdateInternetRadioStation
        /// </summary>
        [Fact]
        public void UpdateInternetRadioStationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string streamUrl = null;
            //string name = null;
            //string? homepageUrl = null;
            //var response = instance.UpdateInternetRadioStation(id, streamUrl, name, homepageUrl);
            //Assert.IsType<SubsonicResponse>(response);
        }
    }
}
