/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using WinSonic.Subsonic.Client.Client;
using WinSonic.Subsonic.Client.Api;
// uncomment below to import models
//using WinSonic.Subsonic.Client.Model;

namespace WinSonic.Subsonic.Client.Test.Api
{
    /// <summary>
    ///  Class for testing JukeboxApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class JukeboxApiTests : IDisposable
    {
        private JukeboxApi instance;

        public JukeboxApiTests()
        {
            instance = new JukeboxApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JukeboxApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' JukeboxApi
            //Assert.IsType<JukeboxApi>(instance);
        }

        /// <summary>
        /// Test JukeboxControl
        /// </summary>
        [Fact]
        public void JukeboxControlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //JukeboxAction action = null;
            //int? index = null;
            //int? offset = null;
            //List<string>? id = null;
            //float? gain = null;
            //var response = instance.JukeboxControl(action, index, offset, id, gain);
            //Assert.IsType<JukeboxControlResponse>(response);
        }

        /// <summary>
        /// Test PostJukeboxControl
        /// </summary>
        [Fact]
        public void PostJukeboxControlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object? action = null;
            //int? index = null;
            //int? offset = null;
            //List<string>? id = null;
            //float? gain = null;
            //var response = instance.PostJukeboxControl(action, index, offset, id, gain);
            //Assert.IsType<JukeboxControlResponse>(response);
        }
    }
}
