/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using WinSonic.Subsonic.Client.Client;
using WinSonic.Subsonic.Client.Api;
// uncomment below to import models
//using WinSonic.Subsonic.Client.Model;

namespace WinSonic.Subsonic.Client.Test.Api
{
    /// <summary>
    ///  Class for testing PodcastApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PodcastApiTests : IDisposable
    {
        private PodcastApi instance;

        public PodcastApiTests()
        {
            instance = new PodcastApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PodcastApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PodcastApi
            //Assert.IsType<PodcastApi>(instance);
        }

        /// <summary>
        /// Test CreatePodcastChannel
        /// </summary>
        [Fact]
        public void CreatePodcastChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string url = null;
            //var response = instance.CreatePodcastChannel(url);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test DeletePodcastChannel
        /// </summary>
        [Fact]
        public void DeletePodcastChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DeletePodcastChannel(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test DeletePodcastEpisode
        /// </summary>
        [Fact]
        public void DeletePodcastEpisodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DeletePodcastEpisode(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test DownloadPodcastEpisode
        /// </summary>
        [Fact]
        public void DownloadPodcastEpisodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DownloadPodcastEpisode(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test GetNewestPodcasts
        /// </summary>
        [Fact]
        public void GetNewestPodcastsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? count = null;
            //var response = instance.GetNewestPodcasts(count);
            //Assert.IsType<GetNewestPodcastsResponse>(response);
        }

        /// <summary>
        /// Test GetPodcastEpisode
        /// </summary>
        [Fact]
        public void GetPodcastEpisodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetPodcastEpisode(id);
            //Assert.IsType<GetPodcastEpisodeResponse>(response);
        }

        /// <summary>
        /// Test GetPodcasts
        /// </summary>
        [Fact]
        public void GetPodcastsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? id = null;
            //bool? includeEpisodes = null;
            //var response = instance.GetPodcasts(id, includeEpisodes);
            //Assert.IsType<GetPodcastsResponse>(response);
        }

        /// <summary>
        /// Test PostCreatePodcastChannel
        /// </summary>
        [Fact]
        public void PostCreatePodcastChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string url = null;
            //var response = instance.PostCreatePodcastChannel(url);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test PostDeletePodcastChannel
        /// </summary>
        [Fact]
        public void PostDeletePodcastChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.PostDeletePodcastChannel(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test PostDeletePodcastEpisode
        /// </summary>
        [Fact]
        public void PostDeletePodcastEpisodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.PostDeletePodcastEpisode(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test PostDownloadPodcastEpisode
        /// </summary>
        [Fact]
        public void PostDownloadPodcastEpisodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.PostDownloadPodcastEpisode(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test PostGetNewestPodcasts
        /// </summary>
        [Fact]
        public void PostGetNewestPodcastsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? count = null;
            //var response = instance.PostGetNewestPodcasts(count);
            //Assert.IsType<GetNewestPodcastsResponse>(response);
        }

        /// <summary>
        /// Test PostGetPodcastEpisode
        /// </summary>
        [Fact]
        public void PostGetPodcastEpisodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.PostGetPodcastEpisode(id);
            //Assert.IsType<GetPodcastEpisodeResponse>(response);
        }

        /// <summary>
        /// Test PostGetPodcasts
        /// </summary>
        [Fact]
        public void PostGetPodcastsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? id = null;
            //bool? includeEpisodes = null;
            //var response = instance.PostGetPodcasts(id, includeEpisodes);
            //Assert.IsType<GetPodcastsResponse>(response);
        }

        /// <summary>
        /// Test PostRefreshPodcasts
        /// </summary>
        [Fact]
        public void PostRefreshPodcastsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PostRefreshPodcasts();
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test RefreshPodcasts
        /// </summary>
        [Fact]
        public void RefreshPodcastsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.RefreshPodcasts();
            //Assert.IsType<SubsonicResponse>(response);
        }
    }
}
