/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using WinSonic.Subsonic.Client.Client;
using WinSonic.Subsonic.Client.Api;
// uncomment below to import models
//using WinSonic.Subsonic.Client.Model;

namespace WinSonic.Subsonic.Client.Test.Api
{
    /// <summary>
    ///  Class for testing SharingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SharingApiTests : IDisposable
    {
        private SharingApi instance;

        public SharingApiTests()
        {
            instance = new SharingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SharingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SharingApi
            //Assert.IsType<SharingApi>(instance);
        }

        /// <summary>
        /// Test CreateShare
        /// </summary>
        [Fact]
        public void CreateShareTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> id = null;
            //string? description = null;
            //int? expires = null;
            //var response = instance.CreateShare(id, description, expires);
            //Assert.IsType<CreateSharesResponse>(response);
        }

        /// <summary>
        /// Test DeleteShare
        /// </summary>
        [Fact]
        public void DeleteShareTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DeleteShare(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test GetShares
        /// </summary>
        [Fact]
        public void GetSharesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetShares();
            //Assert.IsType<GetSharesResponse>(response);
        }

        /// <summary>
        /// Test PostCreateShare
        /// </summary>
        [Fact]
        public void PostCreateShareTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> id = null;
            //string? description = null;
            //int? expires = null;
            //var response = instance.PostCreateShare(id, description, expires);
            //Assert.IsType<CreateSharesResponse>(response);
        }

        /// <summary>
        /// Test PostDeleteShare
        /// </summary>
        [Fact]
        public void PostDeleteShareTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.PostDeleteShare(id);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test PostGetShares
        /// </summary>
        [Fact]
        public void PostGetSharesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PostGetShares();
            //Assert.IsType<GetSharesResponse>(response);
        }

        /// <summary>
        /// Test PostUpdateShare
        /// </summary>
        [Fact]
        public void PostUpdateShareTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string? description = null;
            //int? expires = null;
            //var response = instance.PostUpdateShare(id, description, expires);
            //Assert.IsType<SubsonicResponse>(response);
        }

        /// <summary>
        /// Test UpdateShare
        /// </summary>
        [Fact]
        public void UpdateShareTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string? description = null;
            //int? expires = null;
            //var response = instance.UpdateShare(id, description, expires);
            //Assert.IsType<SubsonicResponse>(response);
        }
    }
}
