<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies"/>
      <PackageReference Include="System.ComponentModel.Annotations"/>
    </ItemGroup>


</Project>
