/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// Album info.
    /// </summary>
    [DataContract(Name = "AlbumInfo")]
    public partial class AlbumInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlbumInfo" /> class.
        /// </summary>
        /// <param name="notes">Album notes.</param>
        /// <param name="musicBrainzId">Album musicBrainzId.</param>
        /// <param name="lastFmUrl">Album lastFmUrl.</param>
        /// <param name="smallImageUrl">Album smallImageUrl.</param>
        /// <param name="mediumImageUrl">Album mediumImageUrl.</param>
        /// <param name="largeImageUrl">Album largeImageUrl.</param>
        public AlbumInfo(string notes = default, string musicBrainzId = default, string lastFmUrl = default, string smallImageUrl = default, string mediumImageUrl = default, string largeImageUrl = default)
        {
            this.Notes = notes;
            this.MusicBrainzId = musicBrainzId;
            this.LastFmUrl = lastFmUrl;
            this.SmallImageUrl = smallImageUrl;
            this.MediumImageUrl = mediumImageUrl;
            this.LargeImageUrl = largeImageUrl;
        }

        /// <summary>
        /// Album notes
        /// </summary>
        /// <value>Album notes</value>
        [DataMember(Name = "notes", EmitDefaultValue = false)]
        public string Notes { get; set; }

        /// <summary>
        /// Album musicBrainzId
        /// </summary>
        /// <value>Album musicBrainzId</value>
        [DataMember(Name = "musicBrainzId", EmitDefaultValue = false)]
        public string MusicBrainzId { get; set; }

        /// <summary>
        /// Album lastFmUrl
        /// </summary>
        /// <value>Album lastFmUrl</value>
        [DataMember(Name = "lastFmUrl", EmitDefaultValue = false)]
        public string LastFmUrl { get; set; }

        /// <summary>
        /// Album smallImageUrl
        /// </summary>
        /// <value>Album smallImageUrl</value>
        [DataMember(Name = "smallImageUrl", EmitDefaultValue = false)]
        public string SmallImageUrl { get; set; }

        /// <summary>
        /// Album mediumImageUrl
        /// </summary>
        /// <value>Album mediumImageUrl</value>
        [DataMember(Name = "mediumImageUrl", EmitDefaultValue = false)]
        public string MediumImageUrl { get; set; }

        /// <summary>
        /// Album largeImageUrl
        /// </summary>
        /// <value>Album largeImageUrl</value>
        [DataMember(Name = "largeImageUrl", EmitDefaultValue = false)]
        public string LargeImageUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AlbumInfo {\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  MusicBrainzId: ").Append(MusicBrainzId).Append("\n");
            sb.Append("  LastFmUrl: ").Append(LastFmUrl).Append("\n");
            sb.Append("  SmallImageUrl: ").Append(SmallImageUrl).Append("\n");
            sb.Append("  MediumImageUrl: ").Append(MediumImageUrl).Append("\n");
            sb.Append("  LargeImageUrl: ").Append(LargeImageUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
