/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// AlbumList2
    /// </summary>
    [DataContract(Name = "AlbumList2")]
    public partial class AlbumList2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlbumList2" /> class.
        /// </summary>
        /// <param name="album">Artist albums.</param>
        public AlbumList2(List<AlbumID3> album = default)
        {
            this.Album = album;
        }

        /// <summary>
        /// Artist albums
        /// </summary>
        /// <value>Artist albums</value>
        [DataMember(Name = "album", EmitDefaultValue = false)]
        public List<AlbumID3> Album { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AlbumList2 {\n");
            sb.Append("  Album: ").Append(Album).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
