/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// Bookmarks list.
    /// </summary>
    [DataContract(Name = "Bookmarks")]
    public partial class Bookmarks : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Bookmarks" /> class.
        /// </summary>
        /// <param name="bookmark">List of bookmark.</param>
        public Bookmarks(List<Bookmark> bookmark = default)
        {
            this.Bookmark = bookmark;
        }

        /// <summary>
        /// List of bookmark
        /// </summary>
        /// <value>List of bookmark</value>
        [DataMember(Name = "bookmark", EmitDefaultValue = false)]
        public List<Bookmark> Bookmark { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Bookmarks {\n");
            sb.Append("  Bookmark: ").Append(Bookmark).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
