/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// Word/syllable-level timing data for a lyrics line
    /// </summary>
    [DataContract(Name = "CueLine")]
    public partial class CueLine : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CueLine" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CueLine() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CueLine" /> class.
        /// </summary>
        /// <param name="index">Zero-based index into the parent line array this cueLine corresponds to (required).</param>
        /// <param name="start">Start time in milliseconds (may differ from the parent line if cues are more precise).</param>
        /// <param name="end">End time in milliseconds.</param>
        /// <param name="value">Required full text of the line. Nested cue byteStart and byteEnd offsets are always calculated against this exact final UTF-8 string (required).</param>
        /// <param name="agentId">Opaque identifier referencing an agent in the same structuredLyrics entry. If the parent structuredLyrics entry includes agents, every cueLine in that entry must include agentId, and the value must match exactly one agents[].id in that entry. If the parent entry does not include agents, cueLines must not include agentId. When multiple cueLines share the same index, the cueLine whose referenced agent has role main must come first.</param>
        /// <param name="cue">Ordered list of word/syllable cues. Every cue includes required byteStart and byteEnd offsets into value (required).</param>
        public CueLine(int index = default, int start = default, int end = default, string value = default, string agentId = default, List<Cue> cue = default)
        {
            this.Index = index;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for CueLine and cannot be null");
            }
            this.Value = value;
            // to ensure "cue" is required (not null)
            if (cue == null)
            {
                throw new ArgumentNullException("cue is a required property for CueLine and cannot be null");
            }
            this.Cue = cue;
            this.Start = start;
            this.End = end;
            this.AgentId = agentId;
        }

        /// <summary>
        /// Zero-based index into the parent line array this cueLine corresponds to
        /// </summary>
        /// <value>Zero-based index into the parent line array this cueLine corresponds to</value>
        [DataMember(Name = "index", IsRequired = true, EmitDefaultValue = true)]
        public int Index { get; set; }

        /// <summary>
        /// Start time in milliseconds (may differ from the parent line if cues are more precise)
        /// </summary>
        /// <value>Start time in milliseconds (may differ from the parent line if cues are more precise)</value>
        [DataMember(Name = "start", EmitDefaultValue = false)]
        public int Start { get; set; }

        /// <summary>
        /// End time in milliseconds
        /// </summary>
        /// <value>End time in milliseconds</value>
        [DataMember(Name = "end", EmitDefaultValue = false)]
        public int End { get; set; }

        /// <summary>
        /// Required full text of the line. Nested cue byteStart and byteEnd offsets are always calculated against this exact final UTF-8 string
        /// </summary>
        /// <value>Required full text of the line. Nested cue byteStart and byteEnd offsets are always calculated against this exact final UTF-8 string</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Opaque identifier referencing an agent in the same structuredLyrics entry. If the parent structuredLyrics entry includes agents, every cueLine in that entry must include agentId, and the value must match exactly one agents[].id in that entry. If the parent entry does not include agents, cueLines must not include agentId. When multiple cueLines share the same index, the cueLine whose referenced agent has role main must come first
        /// </summary>
        /// <value>Opaque identifier referencing an agent in the same structuredLyrics entry. If the parent structuredLyrics entry includes agents, every cueLine in that entry must include agentId, and the value must match exactly one agents[].id in that entry. If the parent entry does not include agents, cueLines must not include agentId. When multiple cueLines share the same index, the cueLine whose referenced agent has role main must come first</value>
        [DataMember(Name = "agentId", EmitDefaultValue = false)]
        public string AgentId { get; set; }

        /// <summary>
        /// Ordered list of word/syllable cues. Every cue includes required byteStart and byteEnd offsets into value
        /// </summary>
        /// <value>Ordered list of word/syllable cues. Every cue includes required byteStart and byteEnd offsets into value</value>
        [DataMember(Name = "cue", IsRequired = true, EmitDefaultValue = true)]
        public List<Cue> Cue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CueLine {\n");
            sb.Append("  Index: ").Append(Index).Append("\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  AgentId: ").Append(AgentId).Append("\n");
            sb.Append("  Cue: ").Append(Cue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
