/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// The generic type of media [music/podcast/audiobook/video]
    /// </summary>
    /// <value>The generic type of media [music/podcast/audiobook/video]</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GenericMediaType
    {
        /// <summary>
        /// Enum Music for value: music
        /// </summary>
        [EnumMember(Value = "music")]
        Music = 1,

        /// <summary>
        /// Enum Video for value: video
        /// </summary>
        [EnumMember(Value = "video")]
        Video = 2,

        /// <summary>
        /// Enum Podcast for value: podcast
        /// </summary>
        [EnumMember(Value = "podcast")]
        Podcast = 3,

        /// <summary>
        /// Enum Audiobook for value: audiobook
        /// </summary>
        [EnumMember(Value = "audiobook")]
        Audiobook = 4
    }

}
