/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// A genre.
    /// </summary>
    [DataContract(Name = "Genre")]
    public partial class Genre : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Genre" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Genre() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Genre" /> class.
        /// </summary>
        /// <param name="value">Genre name (required).</param>
        /// <param name="songCount">Genre song count (required).</param>
        /// <param name="albumCount">Genre album count (required).</param>
        public Genre(string value = default, int songCount = default, int albumCount = default)
        {
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for Genre and cannot be null");
            }
            this.Value = value;
            this.SongCount = songCount;
            this.AlbumCount = albumCount;
        }

        /// <summary>
        /// Genre name
        /// </summary>
        /// <value>Genre name</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Genre song count
        /// </summary>
        /// <value>Genre song count</value>
        [DataMember(Name = "songCount", IsRequired = true, EmitDefaultValue = true)]
        public int SongCount { get; set; }

        /// <summary>
        /// Genre album count
        /// </summary>
        /// <value>Genre album count</value>
        [DataMember(Name = "albumCount", IsRequired = true, EmitDefaultValue = true)]
        public int AlbumCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Genre {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  SongCount: ").Append(SongCount).Append("\n");
            sb.Append("  AlbumCount: ").Append(AlbumCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
