/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// A subsonic-response element with a nested artist element on success.
    /// </summary>
    [DataContract(Name = "GetArtistResponse")]
    public partial class GetArtistResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetArtistResponse" /> class.
        /// </summary>
        /// <param name="subsonicResponse">subsonicResponse.</param>
        public GetArtistResponse(GetArtistResponseSubsonicResponse subsonicResponse = default)
        {
            this.SubsonicResponse = subsonicResponse;
        }

        /// <summary>
        /// Gets or Sets SubsonicResponse
        /// </summary>
        [DataMember(Name = "subsonic-response", EmitDefaultValue = false)]
        public GetArtistResponseSubsonicResponse SubsonicResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetArtistResponse {\n");
            sb.Append("  SubsonicResponse: ").Append(SubsonicResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
