/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// An indexed artist list by ID3 tags.
    /// </summary>
    [DataContract(Name = "IndexID3")]
    public partial class IndexID3 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IndexID3" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IndexID3() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IndexID3" /> class.
        /// </summary>
        /// <param name="name">Index name (required).</param>
        /// <param name="artist">Artist list.</param>
        public IndexID3(string name = default, List<ArtistID3> artist = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for IndexID3 and cannot be null");
            }
            this.Name = name;
            this.Artist = artist;
        }

        /// <summary>
        /// Index name
        /// </summary>
        /// <value>Index name</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Artist list
        /// </summary>
        /// <value>Artist list</value>
        [DataMember(Name = "artist", EmitDefaultValue = false)]
        public List<ArtistID3> Artist { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IndexID3 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Artist: ").Append(Artist).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
