/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;
using System.Reflection;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// JukeboxControlResponseSubsonicResponse
    /// </summary>
    [JsonConverter(typeof(JukeboxControlResponseSubsonicResponseJsonConverter))]
    [DataContract(Name = "JukeboxControlResponse_subsonic_response")]
    public partial class JukeboxControlResponseSubsonicResponse : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JukeboxControlResponseSubsonicResponse" /> class
        /// with the <see cref="JukeboxControlSuccessResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of JukeboxControlSuccessResponse.</param>
        public JukeboxControlResponseSubsonicResponse(JukeboxControlSuccessResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JukeboxControlResponseSubsonicResponse" /> class
        /// with the <see cref="SubsonicFailureResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SubsonicFailureResponse.</param>
        public JukeboxControlResponseSubsonicResponse(SubsonicFailureResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(JukeboxControlSuccessResponse) || value is JukeboxControlSuccessResponse)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SubsonicFailureResponse) || value is SubsonicFailureResponse)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: JukeboxControlSuccessResponse, SubsonicFailureResponse");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `JukeboxControlSuccessResponse`. If the actual instance is not `JukeboxControlSuccessResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of JukeboxControlSuccessResponse</returns>
        public JukeboxControlSuccessResponse GetJukeboxControlSuccessResponse()
        {
            return (JukeboxControlSuccessResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SubsonicFailureResponse`. If the actual instance is not `SubsonicFailureResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SubsonicFailureResponse</returns>
        public SubsonicFailureResponse GetSubsonicFailureResponse()
        {
            return (SubsonicFailureResponse)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JukeboxControlResponseSubsonicResponse {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, JukeboxControlResponseSubsonicResponse.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of JukeboxControlResponseSubsonicResponse
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of JukeboxControlResponseSubsonicResponse</returns>
        public static JukeboxControlResponseSubsonicResponse FromJson(string jsonString)
        {
            JukeboxControlResponseSubsonicResponse newJukeboxControlResponseSubsonicResponse = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newJukeboxControlResponseSubsonicResponse;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(JukeboxControlSuccessResponse).GetProperty("AdditionalProperties") == null)
                {
                    newJukeboxControlResponseSubsonicResponse = new JukeboxControlResponseSubsonicResponse(JsonConvert.DeserializeObject<JukeboxControlSuccessResponse>(jsonString, JukeboxControlResponseSubsonicResponse.SerializerSettings));
                }
                else
                {
                    newJukeboxControlResponseSubsonicResponse = new JukeboxControlResponseSubsonicResponse(JsonConvert.DeserializeObject<JukeboxControlSuccessResponse>(jsonString, JukeboxControlResponseSubsonicResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("JukeboxControlSuccessResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into JukeboxControlSuccessResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SubsonicFailureResponse).GetProperty("AdditionalProperties") == null)
                {
                    newJukeboxControlResponseSubsonicResponse = new JukeboxControlResponseSubsonicResponse(JsonConvert.DeserializeObject<SubsonicFailureResponse>(jsonString, JukeboxControlResponseSubsonicResponse.SerializerSettings));
                }
                else
                {
                    newJukeboxControlResponseSubsonicResponse = new JukeboxControlResponseSubsonicResponse(JsonConvert.DeserializeObject<SubsonicFailureResponse>(jsonString, JukeboxControlResponseSubsonicResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SubsonicFailureResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SubsonicFailureResponse: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newJukeboxControlResponseSubsonicResponse;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for JukeboxControlResponseSubsonicResponse
    /// </summary>
    public class JukeboxControlResponseSubsonicResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(JukeboxControlResponseSubsonicResponse).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return JukeboxControlResponseSubsonicResponse.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return JukeboxControlResponseSubsonicResponse.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
