/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// getLicense result.
    /// </summary>
    [DataContract(Name = "License")]
    public partial class License : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="License" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected License() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="License" /> class.
        /// </summary>
        /// <param name="valid">The status of the license (required).</param>
        /// <param name="email">User email.</param>
        /// <param name="licenseExpires">End of license date. [ISO 8601].</param>
        /// <param name="trialExpires">End of trial date. [ISO 8601].</param>
        public License(bool valid = default, string email = default, DateTime licenseExpires = default, DateTime trialExpires = default)
        {
            this.Valid = valid;
            this.Email = email;
            this.LicenseExpires = licenseExpires;
            this.TrialExpires = trialExpires;
        }

        /// <summary>
        /// The status of the license
        /// </summary>
        /// <value>The status of the license</value>
        [DataMember(Name = "valid", IsRequired = true, EmitDefaultValue = true)]
        public bool Valid { get; set; }

        /// <summary>
        /// User email
        /// </summary>
        /// <value>User email</value>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// End of license date. [ISO 8601]
        /// </summary>
        /// <value>End of license date. [ISO 8601]</value>
        [DataMember(Name = "licenseExpires", EmitDefaultValue = false)]
        public DateTime LicenseExpires { get; set; }

        /// <summary>
        /// End of trial date. [ISO 8601]
        /// </summary>
        /// <value>End of trial date. [ISO 8601]</value>
        [DataMember(Name = "trialExpires", EmitDefaultValue = false)]
        public DateTime TrialExpires { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class License {\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  LicenseExpires: ").Append(LicenseExpires).Append("\n");
            sb.Append("  TrialExpires: ").Append(TrialExpires).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
