/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// NowPlayingEntry
    /// </summary>
    [DataContract(Name = "NowPlayingEntry")]
    public partial class NowPlayingEntry : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public GenericMediaType? Type { get; set; }

        /// <summary>
        /// Gets or Sets MediaType
        /// </summary>
        [DataMember(Name = "mediaType", EmitDefaultValue = false)]
        public MediaType? MediaType { get; set; }

        /// <summary>
        /// Gets or Sets ExplicitStatus
        /// </summary>
        [DataMember(Name = "explicitStatus", EmitDefaultValue = false)]
        public ExplicitStatus? ExplicitStatus { get; set; }
        /// <summary>
        /// Playback state.
        /// </summary>
        /// <value>Playback state.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            /// <summary>
            /// Enum Starting for value: starting
            /// </summary>
            [EnumMember(Value = "starting")]
            Starting = 1,

            /// <summary>
            /// Enum Playing for value: playing
            /// </summary>
            [EnumMember(Value = "playing")]
            Playing = 2,

            /// <summary>
            /// Enum Paused for value: paused
            /// </summary>
            [EnumMember(Value = "paused")]
            Paused = 3,

            /// <summary>
            /// Enum Stopped for value: stopped
            /// </summary>
            [EnumMember(Value = "stopped")]
            Stopped = 4
        }


        /// <summary>
        /// Playback state.
        /// </summary>
        /// <value>Playback state.</value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="NowPlayingEntry" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NowPlayingEntry() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NowPlayingEntry" /> class.
        /// </summary>
        /// <param name="id">The id of the media. (required).</param>
        /// <param name="parent">The id of the parent (folder/album).</param>
        /// <param name="isDir">The media is a directory (required).</param>
        /// <param name="title">The media name. (required).</param>
        /// <param name="album">The album name..</param>
        /// <param name="artist">The artist name..</param>
        /// <param name="track">The track number..</param>
        /// <param name="year">The media year..</param>
        /// <param name="genre">The media genre.</param>
        /// <param name="coverArt">The coverArt id..</param>
        /// <param name="size">A file size of the media..</param>
        /// <param name="contentType">The mimeType of the media..</param>
        /// <param name="suffix">The file suffix of the media..</param>
        /// <param name="transcodedContentType">The transcoded mediaType if transcoding should happen..</param>
        /// <param name="transcodedSuffix">The file suffix of the transcoded media..</param>
        /// <param name="duration">The duration of the media in seconds..</param>
        /// <param name="bitRate">The bitrate of the media..</param>
        /// <param name="bitDepth">The bit depth of the media..</param>
        /// <param name="samplingRate">The sampling rate of the media..</param>
        /// <param name="channelCount">The number of channels of the media..</param>
        /// <param name="path">The full path of the media..</param>
        /// <param name="isVideo">Media is a video.</param>
        /// <param name="userRating">The user rating of the media [1-5].</param>
        /// <param name="averageRating">The average rating of the media [1.0-5.0].</param>
        /// <param name="playCount">The play count..</param>
        /// <param name="discNumber">The disc number..</param>
        /// <param name="created">Date the media was created. [ISO 8601].</param>
        /// <param name="starred">Date the media was starred. [ISO 8601].</param>
        /// <param name="albumId">The corresponding album id.</param>
        /// <param name="artistId">The corresponding artist id.</param>
        /// <param name="type">type.</param>
        /// <param name="mediaType">mediaType.</param>
        /// <param name="bookmarkPosition">The bookmark position in seconds.</param>
        /// <param name="originalWidth">The video original Width.</param>
        /// <param name="originalHeight">The video original Height.</param>
        /// <param name="played">Date the album was last played. [ISO 8601].</param>
        /// <param name="bpm">The BPM of the song..</param>
        /// <param name="comment">The comment tag of the song..</param>
        /// <param name="sortName">The song sort name..</param>
        /// <param name="musicBrainzId">The track MusicBrainzID..</param>
        /// <param name="isrc">The track ISRC(s)..</param>
        /// <param name="genres">The list of all genres of the song..</param>
        /// <param name="artists">The list of all song artists of the song. (Note: Only the required &#x60;ArtistID3&#x60; fields should be returned by default).</param>
        /// <param name="displayArtist">The single value display artist..</param>
        /// <param name="albumArtists">The list of all album artists of the song. (Note: Only the required &#x60;ArtistID3&#x60; fields should be returned by default).</param>
        /// <param name="displayAlbumArtist">The single value display album artist..</param>
        /// <param name="contributors">The list of all contributor artists of the song..</param>
        /// <param name="displayComposer">The single value display composer..</param>
        /// <param name="moods">The list of all moods of the song..</param>
        /// <param name="replayGain">The replay gain data of the song..</param>
        /// <param name="explicitStatus">explicitStatus.</param>
        /// <param name="works">The list of works associated with the song..</param>
        /// <param name="movements">The list of movements associated with the song..</param>
        /// <param name="groupings">The list of groupings associated with the song..</param>
        /// <param name="username">The username (required).</param>
        /// <param name="minutesAgo">Last update (required).</param>
        /// <param name="playerId">Player Id (required).</param>
        /// <param name="playerName">Player name.</param>
        /// <param name="state">Playback state..</param>
        /// <param name="positionMs">Current playback position in milliseconds (Calculated by the server from the last playbackReport call received).</param>
        /// <param name="playbackRate">Playback speed multiplier.</param>
        public NowPlayingEntry(string id = default, string parent = default, bool isDir = default, string title = default, string album = default, string artist = default, int track = default, int year = default, string genre = default, string coverArt = default, int size = default, string contentType = default, string suffix = default, string transcodedContentType = default, string transcodedSuffix = default, int duration = default, int bitRate = default, int bitDepth = default, int samplingRate = default, int channelCount = default, string path = default, bool isVideo = default, int userRating = default, decimal averageRating = default, int playCount = default, int discNumber = default, DateTime created = default, DateTime starred = default, string albumId = default, string artistId = default, GenericMediaType? type = default, MediaType? mediaType = default, int bookmarkPosition = default, int originalWidth = default, int originalHeight = default, DateTime played = default, int bpm = default, string comment = default, string sortName = default, string musicBrainzId = default, List<string> isrc = default, List<ItemGenre> genres = default, List<ArtistID3> artists = default, string displayArtist = default, List<ArtistID3> albumArtists = default, string displayAlbumArtist = default, List<Contributor> contributors = default, string displayComposer = default, List<string> moods = default, ReplayGain replayGain = default, ExplicitStatus? explicitStatus = default, List<Work> works = default, List<Movement> movements = default, List<string> groupings = default, string username = default, int minutesAgo = default, int playerId = default, string playerName = default, StateEnum? state = default, int positionMs = default, float playbackRate = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for NowPlayingEntry and cannot be null");
            }
            this.Id = id;
            this.IsDir = isDir;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for NowPlayingEntry and cannot be null");
            }
            this.Title = title;
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for NowPlayingEntry and cannot be null");
            }
            this.Username = username;
            this.MinutesAgo = minutesAgo;
            this.PlayerId = playerId;
            this.Parent = parent;
            this.Album = album;
            this.Artist = artist;
            this.Track = track;
            this.Year = year;
            this.Genre = genre;
            this.CoverArt = coverArt;
            this.Size = size;
            this.ContentType = contentType;
            this.Suffix = suffix;
            this.TranscodedContentType = transcodedContentType;
            this.TranscodedSuffix = transcodedSuffix;
            this.Duration = duration;
            this.BitRate = bitRate;
            this.BitDepth = bitDepth;
            this.SamplingRate = samplingRate;
            this.ChannelCount = channelCount;
            this.Path = path;
            this.IsVideo = isVideo;
            this.UserRating = userRating;
            this.AverageRating = averageRating;
            this.PlayCount = playCount;
            this.DiscNumber = discNumber;
            this.Created = created;
            this.Starred = starred;
            this.AlbumId = albumId;
            this.ArtistId = artistId;
            this.Type = type;
            this.MediaType = mediaType;
            this.BookmarkPosition = bookmarkPosition;
            this.OriginalWidth = originalWidth;
            this.OriginalHeight = originalHeight;
            this.Played = played;
            this.Bpm = bpm;
            this.Comment = comment;
            this.SortName = sortName;
            this.MusicBrainzId = musicBrainzId;
            this.Isrc = isrc;
            this.Genres = genres;
            this.Artists = artists;
            this.DisplayArtist = displayArtist;
            this.AlbumArtists = albumArtists;
            this.DisplayAlbumArtist = displayAlbumArtist;
            this.Contributors = contributors;
            this.DisplayComposer = displayComposer;
            this.Moods = moods;
            this.ReplayGain = replayGain;
            this.ExplicitStatus = explicitStatus;
            this.Works = works;
            this.Movements = movements;
            this.Groupings = groupings;
            this.PlayerName = playerName;
            this.State = state;
            this.PositionMs = positionMs;
            this.PlaybackRate = playbackRate;
        }

        /// <summary>
        /// The id of the media.
        /// </summary>
        /// <value>The id of the media.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The id of the parent (folder/album)
        /// </summary>
        /// <value>The id of the parent (folder/album)</value>
        [DataMember(Name = "parent", EmitDefaultValue = false)]
        public string Parent { get; set; }

        /// <summary>
        /// The media is a directory
        /// </summary>
        /// <value>The media is a directory</value>
        [DataMember(Name = "isDir", IsRequired = true, EmitDefaultValue = true)]
        public bool IsDir { get; set; }

        /// <summary>
        /// The media name.
        /// </summary>
        /// <value>The media name.</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// The album name.
        /// </summary>
        /// <value>The album name.</value>
        [DataMember(Name = "album", EmitDefaultValue = false)]
        public string Album { get; set; }

        /// <summary>
        /// The artist name.
        /// </summary>
        /// <value>The artist name.</value>
        [DataMember(Name = "artist", EmitDefaultValue = false)]
        public string Artist { get; set; }

        /// <summary>
        /// The track number.
        /// </summary>
        /// <value>The track number.</value>
        [DataMember(Name = "track", EmitDefaultValue = false)]
        public int Track { get; set; }

        /// <summary>
        /// The media year.
        /// </summary>
        /// <value>The media year.</value>
        [DataMember(Name = "year", EmitDefaultValue = false)]
        public int Year { get; set; }

        /// <summary>
        /// The media genre
        /// </summary>
        /// <value>The media genre</value>
        [DataMember(Name = "genre", EmitDefaultValue = false)]
        public string Genre { get; set; }

        /// <summary>
        /// The coverArt id.
        /// </summary>
        /// <value>The coverArt id.</value>
        [DataMember(Name = "coverArt", EmitDefaultValue = false)]
        public string CoverArt { get; set; }

        /// <summary>
        /// A file size of the media.
        /// </summary>
        /// <value>A file size of the media.</value>
        [DataMember(Name = "size", EmitDefaultValue = false)]
        public int Size { get; set; }

        /// <summary>
        /// The mimeType of the media.
        /// </summary>
        /// <value>The mimeType of the media.</value>
        [DataMember(Name = "contentType", EmitDefaultValue = false)]
        public string ContentType { get; set; }

        /// <summary>
        /// The file suffix of the media.
        /// </summary>
        /// <value>The file suffix of the media.</value>
        [DataMember(Name = "suffix", EmitDefaultValue = false)]
        public string Suffix { get; set; }

        /// <summary>
        /// The transcoded mediaType if transcoding should happen.
        /// </summary>
        /// <value>The transcoded mediaType if transcoding should happen.</value>
        [DataMember(Name = "transcodedContentType", EmitDefaultValue = false)]
        public string TranscodedContentType { get; set; }

        /// <summary>
        /// The file suffix of the transcoded media.
        /// </summary>
        /// <value>The file suffix of the transcoded media.</value>
        [DataMember(Name = "transcodedSuffix", EmitDefaultValue = false)]
        public string TranscodedSuffix { get; set; }

        /// <summary>
        /// The duration of the media in seconds.
        /// </summary>
        /// <value>The duration of the media in seconds.</value>
        [DataMember(Name = "duration", EmitDefaultValue = false)]
        public int Duration { get; set; }

        /// <summary>
        /// The bitrate of the media.
        /// </summary>
        /// <value>The bitrate of the media.</value>
        [DataMember(Name = "bitRate", EmitDefaultValue = false)]
        public int BitRate { get; set; }

        /// <summary>
        /// The bit depth of the media.
        /// </summary>
        /// <value>The bit depth of the media.</value>
        [DataMember(Name = "bitDepth", EmitDefaultValue = false)]
        public int BitDepth { get; set; }

        /// <summary>
        /// The sampling rate of the media.
        /// </summary>
        /// <value>The sampling rate of the media.</value>
        [DataMember(Name = "samplingRate", EmitDefaultValue = false)]
        public int SamplingRate { get; set; }

        /// <summary>
        /// The number of channels of the media.
        /// </summary>
        /// <value>The number of channels of the media.</value>
        [DataMember(Name = "channelCount", EmitDefaultValue = false)]
        public int ChannelCount { get; set; }

        /// <summary>
        /// The full path of the media.
        /// </summary>
        /// <value>The full path of the media.</value>
        [DataMember(Name = "path", EmitDefaultValue = false)]
        public string Path { get; set; }

        /// <summary>
        /// Media is a video
        /// </summary>
        /// <value>Media is a video</value>
        [DataMember(Name = "isVideo", EmitDefaultValue = true)]
        public bool IsVideo { get; set; }

        /// <summary>
        /// The user rating of the media [1-5]
        /// </summary>
        /// <value>The user rating of the media [1-5]</value>
        [DataMember(Name = "userRating", EmitDefaultValue = false)]
        public int UserRating { get; set; }

        /// <summary>
        /// The average rating of the media [1.0-5.0]
        /// </summary>
        /// <value>The average rating of the media [1.0-5.0]</value>
        [DataMember(Name = "averageRating", EmitDefaultValue = false)]
        public decimal AverageRating { get; set; }

        /// <summary>
        /// The play count.
        /// </summary>
        /// <value>The play count.</value>
        [DataMember(Name = "playCount", EmitDefaultValue = false)]
        public int PlayCount { get; set; }

        /// <summary>
        /// The disc number.
        /// </summary>
        /// <value>The disc number.</value>
        [DataMember(Name = "discNumber", EmitDefaultValue = false)]
        public int DiscNumber { get; set; }

        /// <summary>
        /// Date the media was created. [ISO 8601]
        /// </summary>
        /// <value>Date the media was created. [ISO 8601]</value>
        [DataMember(Name = "created", EmitDefaultValue = false)]
        public DateTime Created { get; set; }

        /// <summary>
        /// Date the media was starred. [ISO 8601]
        /// </summary>
        /// <value>Date the media was starred. [ISO 8601]</value>
        [DataMember(Name = "starred", EmitDefaultValue = false)]
        public DateTime Starred { get; set; }

        /// <summary>
        /// The corresponding album id
        /// </summary>
        /// <value>The corresponding album id</value>
        [DataMember(Name = "albumId", EmitDefaultValue = false)]
        public string AlbumId { get; set; }

        /// <summary>
        /// The corresponding artist id
        /// </summary>
        /// <value>The corresponding artist id</value>
        [DataMember(Name = "artistId", EmitDefaultValue = false)]
        public string ArtistId { get; set; }

        /// <summary>
        /// The bookmark position in seconds
        /// </summary>
        /// <value>The bookmark position in seconds</value>
        [DataMember(Name = "bookmarkPosition", EmitDefaultValue = false)]
        public int BookmarkPosition { get; set; }

        /// <summary>
        /// The video original Width
        /// </summary>
        /// <value>The video original Width</value>
        [DataMember(Name = "originalWidth", EmitDefaultValue = false)]
        public int OriginalWidth { get; set; }

        /// <summary>
        /// The video original Height
        /// </summary>
        /// <value>The video original Height</value>
        [DataMember(Name = "originalHeight", EmitDefaultValue = false)]
        public int OriginalHeight { get; set; }

        /// <summary>
        /// Date the album was last played. [ISO 8601]
        /// </summary>
        /// <value>Date the album was last played. [ISO 8601]</value>
        [DataMember(Name = "played", EmitDefaultValue = false)]
        public DateTime Played { get; set; }

        /// <summary>
        /// The BPM of the song.
        /// </summary>
        /// <value>The BPM of the song.</value>
        [DataMember(Name = "bpm", EmitDefaultValue = false)]
        public int Bpm { get; set; }

        /// <summary>
        /// The comment tag of the song.
        /// </summary>
        /// <value>The comment tag of the song.</value>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// The song sort name.
        /// </summary>
        /// <value>The song sort name.</value>
        [DataMember(Name = "sortName", EmitDefaultValue = false)]
        public string SortName { get; set; }

        /// <summary>
        /// The track MusicBrainzID.
        /// </summary>
        /// <value>The track MusicBrainzID.</value>
        [DataMember(Name = "musicBrainzId", EmitDefaultValue = false)]
        public string MusicBrainzId { get; set; }

        /// <summary>
        /// The track ISRC(s).
        /// </summary>
        /// <value>The track ISRC(s).</value>
        /*
        <example>[USSM18300073, DELV42300297]</example>
        */
        [DataMember(Name = "isrc", EmitDefaultValue = false)]
        public List<string> Isrc { get; set; }

        /// <summary>
        /// The list of all genres of the song.
        /// </summary>
        /// <value>The list of all genres of the song.</value>
        [DataMember(Name = "genres", EmitDefaultValue = false)]
        public List<ItemGenre> Genres { get; set; }

        /// <summary>
        /// The list of all song artists of the song. (Note: Only the required &#x60;ArtistID3&#x60; fields should be returned by default)
        /// </summary>
        /// <value>The list of all song artists of the song. (Note: Only the required &#x60;ArtistID3&#x60; fields should be returned by default)</value>
        [DataMember(Name = "artists", EmitDefaultValue = false)]
        public List<ArtistID3> Artists { get; set; }

        /// <summary>
        /// The single value display artist.
        /// </summary>
        /// <value>The single value display artist.</value>
        [DataMember(Name = "displayArtist", EmitDefaultValue = false)]
        public string DisplayArtist { get; set; }

        /// <summary>
        /// The list of all album artists of the song. (Note: Only the required &#x60;ArtistID3&#x60; fields should be returned by default)
        /// </summary>
        /// <value>The list of all album artists of the song. (Note: Only the required &#x60;ArtistID3&#x60; fields should be returned by default)</value>
        [DataMember(Name = "albumArtists", EmitDefaultValue = false)]
        public List<ArtistID3> AlbumArtists { get; set; }

        /// <summary>
        /// The single value display album artist.
        /// </summary>
        /// <value>The single value display album artist.</value>
        [DataMember(Name = "displayAlbumArtist", EmitDefaultValue = false)]
        public string DisplayAlbumArtist { get; set; }

        /// <summary>
        /// The list of all contributor artists of the song.
        /// </summary>
        /// <value>The list of all contributor artists of the song.</value>
        [DataMember(Name = "contributors", EmitDefaultValue = false)]
        public List<Contributor> Contributors { get; set; }

        /// <summary>
        /// The single value display composer.
        /// </summary>
        /// <value>The single value display composer.</value>
        [DataMember(Name = "displayComposer", EmitDefaultValue = false)]
        public string DisplayComposer { get; set; }

        /// <summary>
        /// The list of all moods of the song.
        /// </summary>
        /// <value>The list of all moods of the song.</value>
        [DataMember(Name = "moods", EmitDefaultValue = false)]
        public List<string> Moods { get; set; }

        /// <summary>
        /// The replay gain data of the song.
        /// </summary>
        /// <value>The replay gain data of the song.</value>
        [DataMember(Name = "replayGain", EmitDefaultValue = false)]
        public ReplayGain ReplayGain { get; set; }

        /// <summary>
        /// The list of works associated with the song.
        /// </summary>
        /// <value>The list of works associated with the song.</value>
        [DataMember(Name = "works", EmitDefaultValue = false)]
        public List<Work> Works { get; set; }

        /// <summary>
        /// The list of movements associated with the song.
        /// </summary>
        /// <value>The list of movements associated with the song.</value>
        [DataMember(Name = "movements", EmitDefaultValue = false)]
        public List<Movement> Movements { get; set; }

        /// <summary>
        /// The list of groupings associated with the song.
        /// </summary>
        /// <value>The list of groupings associated with the song.</value>
        [DataMember(Name = "groupings", EmitDefaultValue = false)]
        public List<string> Groupings { get; set; }

        /// <summary>
        /// The username
        /// </summary>
        /// <value>The username</value>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Last update
        /// </summary>
        /// <value>Last update</value>
        [DataMember(Name = "minutesAgo", IsRequired = true, EmitDefaultValue = true)]
        public int MinutesAgo { get; set; }

        /// <summary>
        /// Player Id
        /// </summary>
        /// <value>Player Id</value>
        [DataMember(Name = "playerId", IsRequired = true, EmitDefaultValue = true)]
        public int PlayerId { get; set; }

        /// <summary>
        /// Player name
        /// </summary>
        /// <value>Player name</value>
        [DataMember(Name = "playerName", EmitDefaultValue = false)]
        public string PlayerName { get; set; }

        /// <summary>
        /// Current playback position in milliseconds (Calculated by the server from the last playbackReport call received)
        /// </summary>
        /// <value>Current playback position in milliseconds (Calculated by the server from the last playbackReport call received)</value>
        [DataMember(Name = "positionMs", EmitDefaultValue = false)]
        public int PositionMs { get; set; }

        /// <summary>
        /// Playback speed multiplier
        /// </summary>
        /// <value>Playback speed multiplier</value>
        [DataMember(Name = "playbackRate", EmitDefaultValue = false)]
        public float PlaybackRate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NowPlayingEntry {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Parent: ").Append(Parent).Append("\n");
            sb.Append("  IsDir: ").Append(IsDir).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Album: ").Append(Album).Append("\n");
            sb.Append("  Artist: ").Append(Artist).Append("\n");
            sb.Append("  Track: ").Append(Track).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  Genre: ").Append(Genre).Append("\n");
            sb.Append("  CoverArt: ").Append(CoverArt).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("  Suffix: ").Append(Suffix).Append("\n");
            sb.Append("  TranscodedContentType: ").Append(TranscodedContentType).Append("\n");
            sb.Append("  TranscodedSuffix: ").Append(TranscodedSuffix).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  BitRate: ").Append(BitRate).Append("\n");
            sb.Append("  BitDepth: ").Append(BitDepth).Append("\n");
            sb.Append("  SamplingRate: ").Append(SamplingRate).Append("\n");
            sb.Append("  ChannelCount: ").Append(ChannelCount).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  IsVideo: ").Append(IsVideo).Append("\n");
            sb.Append("  UserRating: ").Append(UserRating).Append("\n");
            sb.Append("  AverageRating: ").Append(AverageRating).Append("\n");
            sb.Append("  PlayCount: ").Append(PlayCount).Append("\n");
            sb.Append("  DiscNumber: ").Append(DiscNumber).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Starred: ").Append(Starred).Append("\n");
            sb.Append("  AlbumId: ").Append(AlbumId).Append("\n");
            sb.Append("  ArtistId: ").Append(ArtistId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  MediaType: ").Append(MediaType).Append("\n");
            sb.Append("  BookmarkPosition: ").Append(BookmarkPosition).Append("\n");
            sb.Append("  OriginalWidth: ").Append(OriginalWidth).Append("\n");
            sb.Append("  OriginalHeight: ").Append(OriginalHeight).Append("\n");
            sb.Append("  Played: ").Append(Played).Append("\n");
            sb.Append("  Bpm: ").Append(Bpm).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  SortName: ").Append(SortName).Append("\n");
            sb.Append("  MusicBrainzId: ").Append(MusicBrainzId).Append("\n");
            sb.Append("  Isrc: ").Append(Isrc).Append("\n");
            sb.Append("  Genres: ").Append(Genres).Append("\n");
            sb.Append("  Artists: ").Append(Artists).Append("\n");
            sb.Append("  DisplayArtist: ").Append(DisplayArtist).Append("\n");
            sb.Append("  AlbumArtists: ").Append(AlbumArtists).Append("\n");
            sb.Append("  DisplayAlbumArtist: ").Append(DisplayAlbumArtist).Append("\n");
            sb.Append("  Contributors: ").Append(Contributors).Append("\n");
            sb.Append("  DisplayComposer: ").Append(DisplayComposer).Append("\n");
            sb.Append("  Moods: ").Append(Moods).Append("\n");
            sb.Append("  ReplayGain: ").Append(ReplayGain).Append("\n");
            sb.Append("  ExplicitStatus: ").Append(ExplicitStatus).Append("\n");
            sb.Append("  Works: ").Append(Works).Append("\n");
            sb.Append("  Movements: ").Append(Movements).Append("\n");
            sb.Append("  Groupings: ").Append(Groupings).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  MinutesAgo: ").Append(MinutesAgo).Append("\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  PlayerName: ").Append(PlayerName).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  PositionMs: ").Append(PositionMs).Append("\n");
            sb.Append("  PlaybackRate: ").Append(PlaybackRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // UserRating (int) maximum
            if (this.UserRating > (int)5)
            {
                yield return new ValidationResult("Invalid value for UserRating, must be a value less than or equal to 5.", new [] { "UserRating" });
            }

            // UserRating (int) minimum
            if (this.UserRating < (int)1)
            {
                yield return new ValidationResult("Invalid value for UserRating, must be a value greater than or equal to 1.", new [] { "UserRating" });
            }

            // AverageRating (decimal) maximum
            if (this.AverageRating > (decimal)5)
            {
                yield return new ValidationResult("Invalid value for AverageRating, must be a value less than or equal to 5.", new [] { "AverageRating" });
            }

            // AverageRating (decimal) minimum
            if (this.AverageRating < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for AverageRating, must be a value greater than or equal to 0.", new [] { "AverageRating" });
            }

            yield break;
        }
    }

}
