/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// NowPlayingEntry with queue index.
    /// </summary>
    [DataContract(Name = "PlayQueueByIndex")]
    public partial class PlayQueueByIndex : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayQueueByIndex" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlayQueueByIndex() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayQueueByIndex" /> class.
        /// </summary>
        /// <param name="currentIndex">Index of currently playing track.  This must be provided if one or more entries exists.</param>
        /// <param name="position">Position in milliseconds of currently playing track. If not provided, treat this value as 0.</param>
        /// <param name="username">The user this queue belongs to (required).</param>
        /// <param name="changed">Date modified [ISO 8601] (required).</param>
        /// <param name="changedBy">Name of client app (required).</param>
        /// <param name="entry">The list of songs in the queue.</param>
        public PlayQueueByIndex(int currentIndex = default, int position = default, string username = default, DateTime changed = default, string changedBy = default, List<Child> entry = default)
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for PlayQueueByIndex and cannot be null");
            }
            this.Username = username;
            this.Changed = changed;
            // to ensure "changedBy" is required (not null)
            if (changedBy == null)
            {
                throw new ArgumentNullException("changedBy is a required property for PlayQueueByIndex and cannot be null");
            }
            this.ChangedBy = changedBy;
            this.CurrentIndex = currentIndex;
            this.Position = position;
            this.Entry = entry;
        }

        /// <summary>
        /// Index of currently playing track.  This must be provided if one or more entries exists
        /// </summary>
        /// <value>Index of currently playing track.  This must be provided if one or more entries exists</value>
        [DataMember(Name = "currentIndex", EmitDefaultValue = false)]
        public int CurrentIndex { get; set; }

        /// <summary>
        /// Position in milliseconds of currently playing track. If not provided, treat this value as 0
        /// </summary>
        /// <value>Position in milliseconds of currently playing track. If not provided, treat this value as 0</value>
        [DataMember(Name = "position", EmitDefaultValue = false)]
        public int Position { get; set; }

        /// <summary>
        /// The user this queue belongs to
        /// </summary>
        /// <value>The user this queue belongs to</value>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Date modified [ISO 8601]
        /// </summary>
        /// <value>Date modified [ISO 8601]</value>
        [DataMember(Name = "changed", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Changed { get; set; }

        /// <summary>
        /// Name of client app
        /// </summary>
        /// <value>Name of client app</value>
        [DataMember(Name = "changedBy", IsRequired = true, EmitDefaultValue = true)]
        public string ChangedBy { get; set; }

        /// <summary>
        /// The list of songs in the queue
        /// </summary>
        /// <value>The list of songs in the queue</value>
        [DataMember(Name = "entry", EmitDefaultValue = false)]
        public List<Child> Entry { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayQueueByIndex {\n");
            sb.Append("  CurrentIndex: ").Append(CurrentIndex).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Changed: ").Append(Changed).Append("\n");
            sb.Append("  ChangedBy: ").Append(ChangedBy).Append("\n");
            sb.Append("  Entry: ").Append(Entry).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
