/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// A Podcast channel
    /// </summary>
    [DataContract(Name = "PodcastChannel")]
    public partial class PodcastChannel : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public PodcastStatus Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PodcastChannel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PodcastChannel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PodcastChannel" /> class.
        /// </summary>
        /// <param name="id">The channel ID (required).</param>
        /// <param name="url">Podcast channel URL (required).</param>
        /// <param name="title">The channel title.</param>
        /// <param name="description">The channel description.</param>
        /// <param name="coverArt">ID used for retrieving cover art.</param>
        /// <param name="originalImageUrl">URL for original image of podcast channel.</param>
        /// <param name="status">status (required).</param>
        /// <param name="errorMessage">An error message.</param>
        /// <param name="episode">Podcast episodes with this channel.</param>
        public PodcastChannel(string id = default, string url = default, string title = default, string description = default, string coverArt = default, string originalImageUrl = default, PodcastStatus status = default, string errorMessage = default, List<PodcastEpisode> episode = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for PodcastChannel and cannot be null");
            }
            this.Id = id;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for PodcastChannel and cannot be null");
            }
            this.Url = url;
            this.Status = status;
            this.Title = title;
            this.Description = description;
            this.CoverArt = coverArt;
            this.OriginalImageUrl = originalImageUrl;
            this.ErrorMessage = errorMessage;
            this.Episode = episode;
        }

        /// <summary>
        /// The channel ID
        /// </summary>
        /// <value>The channel ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Podcast channel URL
        /// </summary>
        /// <value>Podcast channel URL</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// The channel title
        /// </summary>
        /// <value>The channel title</value>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// The channel description
        /// </summary>
        /// <value>The channel description</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// ID used for retrieving cover art
        /// </summary>
        /// <value>ID used for retrieving cover art</value>
        [DataMember(Name = "coverArt", EmitDefaultValue = false)]
        public string CoverArt { get; set; }

        /// <summary>
        /// URL for original image of podcast channel
        /// </summary>
        /// <value>URL for original image of podcast channel</value>
        [DataMember(Name = "originalImageUrl", EmitDefaultValue = false)]
        public string OriginalImageUrl { get; set; }

        /// <summary>
        /// An error message
        /// </summary>
        /// <value>An error message</value>
        [DataMember(Name = "errorMessage", EmitDefaultValue = false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Podcast episodes with this channel
        /// </summary>
        /// <value>Podcast episodes with this channel</value>
        [DataMember(Name = "episode", EmitDefaultValue = false)]
        public List<PodcastEpisode> Episode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PodcastChannel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CoverArt: ").Append(CoverArt).Append("\n");
            sb.Append("  OriginalImageUrl: ").Append(OriginalImageUrl).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  Episode: ").Append(Episode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
