/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// searchResult3
    /// </summary>
    [DataContract(Name = "SearchResult3")]
    public partial class SearchResult3 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResult3" /> class.
        /// </summary>
        /// <param name="artist">Matching artists.</param>
        /// <param name="album">Matching albums.</param>
        /// <param name="song">Matching songs.</param>
        public SearchResult3(List<ArtistID3> artist = default, List<AlbumID3> album = default, List<Child> song = default)
        {
            this.Artist = artist;
            this.Album = album;
            this.Song = song;
        }

        /// <summary>
        /// Matching artists
        /// </summary>
        /// <value>Matching artists</value>
        [DataMember(Name = "artist", EmitDefaultValue = false)]
        public List<ArtistID3> Artist { get; set; }

        /// <summary>
        /// Matching albums
        /// </summary>
        /// <value>Matching albums</value>
        [DataMember(Name = "album", EmitDefaultValue = false)]
        public List<AlbumID3> Album { get; set; }

        /// <summary>
        /// Matching songs
        /// </summary>
        /// <value>Matching songs</value>
        [DataMember(Name = "song", EmitDefaultValue = false)]
        public List<Child> Song { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchResult3 {\n");
            sb.Append("  Artist: ").Append(Artist).Append("\n");
            sb.Append("  Album: ").Append(Album).Append("\n");
            sb.Append("  Song: ").Append(Song).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
