/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;
using System.Reflection;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// Search2ResponseSubsonicResponse
    /// </summary>
    [JsonConverter(typeof(Search2ResponseSubsonicResponseJsonConverter))]
    [DataContract(Name = "Search2Response_subsonic_response")]
    public partial class Search2ResponseSubsonicResponse : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Search2ResponseSubsonicResponse" /> class
        /// with the <see cref="Search2SuccessResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Search2SuccessResponse.</param>
        public Search2ResponseSubsonicResponse(Search2SuccessResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Search2ResponseSubsonicResponse" /> class
        /// with the <see cref="SubsonicFailureResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SubsonicFailureResponse.</param>
        public Search2ResponseSubsonicResponse(SubsonicFailureResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(Search2SuccessResponse) || value is Search2SuccessResponse)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SubsonicFailureResponse) || value is SubsonicFailureResponse)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: Search2SuccessResponse, SubsonicFailureResponse");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `Search2SuccessResponse`. If the actual instance is not `Search2SuccessResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Search2SuccessResponse</returns>
        public Search2SuccessResponse GetSearch2SuccessResponse()
        {
            return (Search2SuccessResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SubsonicFailureResponse`. If the actual instance is not `SubsonicFailureResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SubsonicFailureResponse</returns>
        public SubsonicFailureResponse GetSubsonicFailureResponse()
        {
            return (SubsonicFailureResponse)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Search2ResponseSubsonicResponse {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, Search2ResponseSubsonicResponse.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of Search2ResponseSubsonicResponse
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of Search2ResponseSubsonicResponse</returns>
        public static Search2ResponseSubsonicResponse FromJson(string jsonString)
        {
            Search2ResponseSubsonicResponse newSearch2ResponseSubsonicResponse = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newSearch2ResponseSubsonicResponse;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Search2SuccessResponse).GetProperty("AdditionalProperties") == null)
                {
                    newSearch2ResponseSubsonicResponse = new Search2ResponseSubsonicResponse(JsonConvert.DeserializeObject<Search2SuccessResponse>(jsonString, Search2ResponseSubsonicResponse.SerializerSettings));
                }
                else
                {
                    newSearch2ResponseSubsonicResponse = new Search2ResponseSubsonicResponse(JsonConvert.DeserializeObject<Search2SuccessResponse>(jsonString, Search2ResponseSubsonicResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Search2SuccessResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Search2SuccessResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SubsonicFailureResponse).GetProperty("AdditionalProperties") == null)
                {
                    newSearch2ResponseSubsonicResponse = new Search2ResponseSubsonicResponse(JsonConvert.DeserializeObject<SubsonicFailureResponse>(jsonString, Search2ResponseSubsonicResponse.SerializerSettings));
                }
                else
                {
                    newSearch2ResponseSubsonicResponse = new Search2ResponseSubsonicResponse(JsonConvert.DeserializeObject<SubsonicFailureResponse>(jsonString, Search2ResponseSubsonicResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SubsonicFailureResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SubsonicFailureResponse: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newSearch2ResponseSubsonicResponse;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for Search2ResponseSubsonicResponse
    /// </summary>
    public class Search2ResponseSubsonicResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(Search2ResponseSubsonicResponse).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return Search2ResponseSubsonicResponse.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return Search2ResponseSubsonicResponse.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
