/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// The transcoding extension
    /// </summary>
    [DataContract(Name = "Transcoding")]
    public partial class Transcoding : IValidatableObject
    {
        /// <summary>
        /// The name of the extension.
        /// </summary>
        /// <value>The name of the extension.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum NameEnum
        {
            /// <summary>
            /// Enum Transcoding for value: transcoding
            /// </summary>
            [EnumMember(Value = "transcoding")]
            Transcoding = 1
        }


        /// <summary>
        /// The name of the extension.
        /// </summary>
        /// <value>The name of the extension.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public NameEnum Name { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Transcoding" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Transcoding() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Transcoding" /> class.
        /// </summary>
        /// <param name="name">The name of the extension. (required).</param>
        /// <param name="varVersion">The version of the extension. (required).</param>
        /// <param name="endpoints">The endpoints provided by this extension. (required).</param>
        public Transcoding(NameEnum name = default, string varVersion = default, List<string> endpoints = default)
        {
            this.Name = name;
            // to ensure "varVersion" is required (not null)
            if (varVersion == null)
            {
                throw new ArgumentNullException("varVersion is a required property for Transcoding and cannot be null");
            }
            this.VarVersion = varVersion;
            // to ensure "endpoints" is required (not null)
            if (endpoints == null)
            {
                throw new ArgumentNullException("endpoints is a required property for Transcoding and cannot be null");
            }
            this.Endpoints = endpoints;
        }

        /// <summary>
        /// The version of the extension.
        /// </summary>
        /// <value>The version of the extension.</value>
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = true)]
        public string VarVersion { get; set; }

        /// <summary>
        /// The endpoints provided by this extension.
        /// </summary>
        /// <value>The endpoints provided by this extension.</value>
        [DataMember(Name = "endpoints", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Endpoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Transcoding {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Endpoints: ").Append(Endpoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
