/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WinSonic.Subsonic.Client.Client.OpenAPIDateConverter;

namespace WinSonic.Subsonic.Client.Model
{
    /// <summary>
    /// user.
    /// </summary>
    [DataContract(Name = "User")]
    public partial class User : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="User" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected User() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="User" /> class.
        /// </summary>
        /// <param name="username">Username (required).</param>
        /// <param name="scrobblingEnabled">Scrobbling enabled (required).</param>
        /// <param name="maxBitRate">maxBitRate.</param>
        /// <param name="adminRole">Whether the user is an admin (required).</param>
        /// <param name="settingsRole">Whether the user is can edit settings (required).</param>
        /// <param name="downloadRole">Whether the user can download (required).</param>
        /// <param name="uploadRole">Whether the user can upload (required).</param>
        /// <param name="playlistRole">Whether the user can create playlists (required).</param>
        /// <param name="coverArtRole">Whether the user can get cover art (required).</param>
        /// <param name="commentRole">Whether the user can create comments (required).</param>
        /// <param name="podcastRole">Whether the user can create/refresh podcasts (required).</param>
        /// <param name="streamRole">Whether the user can stream (required).</param>
        /// <param name="jukeboxRole">Whether the user can control the jukebox (required).</param>
        /// <param name="shareRole">Whether the user can create a stream (required).</param>
        /// <param name="videoConversionRole">Whether the user can convert videos (required).</param>
        /// <param name="avatarLastChanged">Last time the avatar was changed [ISO 8601].</param>
        /// <param name="folder">Folder ID(s).</param>
        public User(string username = default, bool scrobblingEnabled = default, int maxBitRate = default, bool adminRole = default, bool settingsRole = default, bool downloadRole = default, bool uploadRole = default, bool playlistRole = default, bool coverArtRole = default, bool commentRole = default, bool podcastRole = default, bool streamRole = default, bool jukeboxRole = default, bool shareRole = default, bool videoConversionRole = default, DateTime avatarLastChanged = default, List<int> folder = default)
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for User and cannot be null");
            }
            this.Username = username;
            this.ScrobblingEnabled = scrobblingEnabled;
            this.AdminRole = adminRole;
            this.SettingsRole = settingsRole;
            this.DownloadRole = downloadRole;
            this.UploadRole = uploadRole;
            this.PlaylistRole = playlistRole;
            this.CoverArtRole = coverArtRole;
            this.CommentRole = commentRole;
            this.PodcastRole = podcastRole;
            this.StreamRole = streamRole;
            this.JukeboxRole = jukeboxRole;
            this.ShareRole = shareRole;
            this.VideoConversionRole = videoConversionRole;
            this.MaxBitRate = maxBitRate;
            this.AvatarLastChanged = avatarLastChanged;
            this.Folder = folder;
        }

        /// <summary>
        /// Username
        /// </summary>
        /// <value>Username</value>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Scrobbling enabled
        /// </summary>
        /// <value>Scrobbling enabled</value>
        [DataMember(Name = "scrobblingEnabled", IsRequired = true, EmitDefaultValue = true)]
        public bool ScrobblingEnabled { get; set; }

        /// <summary>
        /// Gets or Sets MaxBitRate
        /// </summary>
        [DataMember(Name = "maxBitRate", EmitDefaultValue = false)]
        public int MaxBitRate { get; set; }

        /// <summary>
        /// Whether the user is an admin
        /// </summary>
        /// <value>Whether the user is an admin</value>
        [DataMember(Name = "adminRole", IsRequired = true, EmitDefaultValue = true)]
        public bool AdminRole { get; set; }

        /// <summary>
        /// Whether the user is can edit settings
        /// </summary>
        /// <value>Whether the user is can edit settings</value>
        [DataMember(Name = "settingsRole", IsRequired = true, EmitDefaultValue = true)]
        public bool SettingsRole { get; set; }

        /// <summary>
        /// Whether the user can download
        /// </summary>
        /// <value>Whether the user can download</value>
        [DataMember(Name = "downloadRole", IsRequired = true, EmitDefaultValue = true)]
        public bool DownloadRole { get; set; }

        /// <summary>
        /// Whether the user can upload
        /// </summary>
        /// <value>Whether the user can upload</value>
        [DataMember(Name = "uploadRole", IsRequired = true, EmitDefaultValue = true)]
        public bool UploadRole { get; set; }

        /// <summary>
        /// Whether the user can create playlists
        /// </summary>
        /// <value>Whether the user can create playlists</value>
        [DataMember(Name = "playlistRole", IsRequired = true, EmitDefaultValue = true)]
        public bool PlaylistRole { get; set; }

        /// <summary>
        /// Whether the user can get cover art
        /// </summary>
        /// <value>Whether the user can get cover art</value>
        [DataMember(Name = "coverArtRole", IsRequired = true, EmitDefaultValue = true)]
        public bool CoverArtRole { get; set; }

        /// <summary>
        /// Whether the user can create comments
        /// </summary>
        /// <value>Whether the user can create comments</value>
        [DataMember(Name = "commentRole", IsRequired = true, EmitDefaultValue = true)]
        public bool CommentRole { get; set; }

        /// <summary>
        /// Whether the user can create/refresh podcasts
        /// </summary>
        /// <value>Whether the user can create/refresh podcasts</value>
        [DataMember(Name = "podcastRole", IsRequired = true, EmitDefaultValue = true)]
        public bool PodcastRole { get; set; }

        /// <summary>
        /// Whether the user can stream
        /// </summary>
        /// <value>Whether the user can stream</value>
        [DataMember(Name = "streamRole", IsRequired = true, EmitDefaultValue = true)]
        public bool StreamRole { get; set; }

        /// <summary>
        /// Whether the user can control the jukebox
        /// </summary>
        /// <value>Whether the user can control the jukebox</value>
        [DataMember(Name = "jukeboxRole", IsRequired = true, EmitDefaultValue = true)]
        public bool JukeboxRole { get; set; }

        /// <summary>
        /// Whether the user can create a stream
        /// </summary>
        /// <value>Whether the user can create a stream</value>
        [DataMember(Name = "shareRole", IsRequired = true, EmitDefaultValue = true)]
        public bool ShareRole { get; set; }

        /// <summary>
        /// Whether the user can convert videos
        /// </summary>
        /// <value>Whether the user can convert videos</value>
        [DataMember(Name = "videoConversionRole", IsRequired = true, EmitDefaultValue = true)]
        public bool VideoConversionRole { get; set; }

        /// <summary>
        /// Last time the avatar was changed [ISO 8601]
        /// </summary>
        /// <value>Last time the avatar was changed [ISO 8601]</value>
        [DataMember(Name = "avatarLastChanged", EmitDefaultValue = false)]
        public DateTime AvatarLastChanged { get; set; }

        /// <summary>
        /// Folder ID(s)
        /// </summary>
        /// <value>Folder ID(s)</value>
        [DataMember(Name = "folder", EmitDefaultValue = false)]
        public List<int> Folder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class User {\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  ScrobblingEnabled: ").Append(ScrobblingEnabled).Append("\n");
            sb.Append("  MaxBitRate: ").Append(MaxBitRate).Append("\n");
            sb.Append("  AdminRole: ").Append(AdminRole).Append("\n");
            sb.Append("  SettingsRole: ").Append(SettingsRole).Append("\n");
            sb.Append("  DownloadRole: ").Append(DownloadRole).Append("\n");
            sb.Append("  UploadRole: ").Append(UploadRole).Append("\n");
            sb.Append("  PlaylistRole: ").Append(PlaylistRole).Append("\n");
            sb.Append("  CoverArtRole: ").Append(CoverArtRole).Append("\n");
            sb.Append("  CommentRole: ").Append(CommentRole).Append("\n");
            sb.Append("  PodcastRole: ").Append(PodcastRole).Append("\n");
            sb.Append("  StreamRole: ").Append(StreamRole).Append("\n");
            sb.Append("  JukeboxRole: ").Append(JukeboxRole).Append("\n");
            sb.Append("  ShareRole: ").Append(ShareRole).Append("\n");
            sb.Append("  VideoConversionRole: ").Append(VideoConversionRole).Append("\n");
            sb.Append("  AvatarLastChanged: ").Append(AvatarLastChanged).Append("\n");
            sb.Append("  Folder: ").Append(Folder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
