<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>WinSonic.Misc.ImageTools</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SixLabors.ImageSharp" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WinSonic.Service\WinSonic.Service.csproj" />
    </ItemGroup>

</Project>
