//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinSonic.Resources.Localisation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WinSonic.Resources.Localisation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string _Settings {
            get {
                return ResourceManager.GetString("_Settings", resourceCulture);
            }
        }
        
        public static string _WinSonicTitle {
            get {
                return ResourceManager.GetString("_WinSonicTitle", resourceCulture);
            }
        }
        
        public static string _WinSonicSubtitle {
            get {
                return ResourceManager.GetString("_WinSonicSubtitle", resourceCulture);
            }
        }
        
        public static string _WinSonicAbout {
            get {
                return ResourceManager.GetString("_WinSonicAbout", resourceCulture);
            }
        }
        
        public static string _Playlists {
            get {
                return ResourceManager.GetString("_Playlists", resourceCulture);
            }
        }
        
        public static string _Albums {
            get {
                return ResourceManager.GetString("_Albums", resourceCulture);
            }
        }
        
        public static string _Artists {
            get {
                return ResourceManager.GetString("_Artists", resourceCulture);
            }
        }
        
        public static string _Tracks {
            get {
                return ResourceManager.GetString("_Tracks", resourceCulture);
            }
        }
        
        public static string _Title {
            get {
                return ResourceManager.GetString("_Title", resourceCulture);
            }
        }
        
        public static string _ArtistOptionalMultiple {
            get {
                return ResourceManager.GetString("_ArtistOptionalMultiple", resourceCulture);
            }
        }
        
        public static string _Artist {
            get {
                return ResourceManager.GetString("_Artist", resourceCulture);
            }
        }
        
        public static string _Album {
            get {
                return ResourceManager.GetString("_Album", resourceCulture);
            }
        }
        
        public static string _Duration {
            get {
                return ResourceManager.GetString("_Duration", resourceCulture);
            }
        }
        
        public static string _LandingTitle {
            get {
                return ResourceManager.GetString("_LandingTitle", resourceCulture);
            }
        }
        
        public static string _ServerConfiguration {
            get {
                return ResourceManager.GetString("_ServerConfiguration", resourceCulture);
            }
        }
        
        public static string _ServerHostname {
            get {
                return ResourceManager.GetString("_ServerHostname", resourceCulture);
            }
        }
        
        public static string _ServerUsername {
            get {
                return ResourceManager.GetString("_ServerUsername", resourceCulture);
            }
        }
        
        public static string _ServerPassword {
            get {
                return ResourceManager.GetString("_ServerPassword", resourceCulture);
            }
        }
        
        public static string _SyncServerTitle {
            get {
                return ResourceManager.GetString("_SyncServerTitle", resourceCulture);
            }
        }
        
        public static string _SyncServerSubtitle {
            get {
                return ResourceManager.GetString("_SyncServerSubtitle", resourceCulture);
            }
        }
        
        public static string _SetupCompleteTitle {
            get {
                return ResourceManager.GetString("_SetupCompleteTitle", resourceCulture);
            }
        }
        
        public static string _SetupCompleteBody {
            get {
                return ResourceManager.GetString("_SetupCompleteBody", resourceCulture);
            }
        }
        
        public static string _WizardWelcomeBody {
            get {
                return ResourceManager.GetString("_WizardWelcomeBody", resourceCulture);
            }
        }
        
        public static string _WizardSecondaryBody {
            get {
                return ResourceManager.GetString("_WizardSecondaryBody", resourceCulture);
            }
        }
        
        public static string _WizardConnectionRequired {
            get {
                return ResourceManager.GetString("_WizardConnectionRequired", resourceCulture);
            }
        }
        
        public static string _WizardConnectionMissingValues {
            get {
                return ResourceManager.GetString("_WizardConnectionMissingValues", resourceCulture);
            }
        }
        
        public static string _WizardConnectionSuccess {
            get {
                return ResourceManager.GetString("_WizardConnectionSuccess", resourceCulture);
            }
        }
        
        public static string _WizardConnectionTesting {
            get {
                return ResourceManager.GetString("_WizardConnectionTesting", resourceCulture);
            }
        }
        
        public static string _WizardConnectionFailed {
            get {
                return ResourceManager.GetString("_WizardConnectionFailed", resourceCulture);
            }
        }
        
        public static string _WizardStepOne {
            get {
                return ResourceManager.GetString("_WizardStepOne", resourceCulture);
            }
        }
        
        public static string _WizardStepTwo {
            get {
                return ResourceManager.GetString("_WizardStepTwo", resourceCulture);
            }
        }
        
        public static string _WizardStepThree {
            get {
                return ResourceManager.GetString("_WizardStepThree", resourceCulture);
            }
        }
        
        public static string _WizardStepFour {
            get {
                return ResourceManager.GetString("_WizardStepFour", resourceCulture);
            }
        }
        
        public static string _WizardCompleteMessage {
            get {
                return ResourceManager.GetString("_WizardCompleteMessage", resourceCulture);
            }
        }
        
        public static string _SyncLibrary {
            get {
                return ResourceManager.GetString("_SyncLibrary", resourceCulture);
            }
        }
        
        public static string _SyncingLibrary {
            get {
                return ResourceManager.GetString("_SyncingLibrary", resourceCulture);
            }
        }
        
        public static string _SyncingLibraryDescription {
            get {
                return ResourceManager.GetString("_SyncingLibraryDescription", resourceCulture);
            }
        }
        
        public static string _LandingGetStarted {
            get {
                return ResourceManager.GetString("_LandingGetStarted", resourceCulture);
            }
        }
        
        public static string _LetsGo {
            get {
                return ResourceManager.GetString("_LetsGo", resourceCulture);
            }
        }
        
        public static string _Next {
            get {
                return ResourceManager.GetString("_Next", resourceCulture);
            }
        }
        
        public static string _Back {
            get {
                return ResourceManager.GetString("_Back", resourceCulture);
            }
        }
        
        public static string _Home {
            get {
                return ResourceManager.GetString("_Home", resourceCulture);
            }
        }
        
        public static string _TestPage {
            get {
                return ResourceManager.GetString("_TestPage", resourceCulture);
            }
        }
        
        public static string _TestConnection {
            get {
                return ResourceManager.GetString("_TestConnection", resourceCulture);
            }
        }
        
        public static string _NowPlaying {
            get {
                return ResourceManager.GetString("_NowPlaying", resourceCulture);
            }
        }
        
        public static string _HoursMinsWordyText {
            get {
                return ResourceManager.GetString("_HoursMinsWordyText", resourceCulture);
            }
        }
        
        public static string _HoursWordy {
            get {
                return ResourceManager.GetString("_HoursWordy", resourceCulture);
            }
        }
        
        public static string _HourWordy {
            get {
                return ResourceManager.GetString("_HourWordy", resourceCulture);
            }
        }
        
        public static string _MinsWordy {
            get {
                return ResourceManager.GetString("_MinsWordy", resourceCulture);
            }
        }
        
        public static string _MinWordy {
            get {
                return ResourceManager.GetString("_MinWordy", resourceCulture);
            }
        }
        
        public static string _SettingsGeneral {
            get {
                return ResourceManager.GetString("_SettingsGeneral", resourceCulture);
            }
        }
        
        public static string _SettingsPlayback {
            get {
                return ResourceManager.GetString("_SettingsPlayback", resourceCulture);
            }
        }
        
        public static string _SettingsServer {
            get {
                return ResourceManager.GetString("_SettingsServer", resourceCulture);
            }
        }
        
        public static string _SaveSettings {
            get {
                return ResourceManager.GetString("_SaveSettings", resourceCulture);
            }
        }
        
        public static string _SettingsSaved {
            get {
                return ResourceManager.GetString("_SettingsSaved", resourceCulture);
            }
        }
        
        public static string _Language {
            get {
                return ResourceManager.GetString("_Language", resourceCulture);
            }
        }
        
        public static string _Theme {
            get {
                return ResourceManager.GetString("_Theme", resourceCulture);
            }
        }
        
        public static string _OutputDevice {
            get {
                return ResourceManager.GetString("_OutputDevice", resourceCulture);
            }
        }
        
        public static string _CheckForUpdates {
            get {
                return ResourceManager.GetString("_CheckForUpdates", resourceCulture);
            }
        }
        
        public static string _SyncLyrics {
            get {
                return ResourceManager.GetString("_SyncLyrics", resourceCulture);
            }
        }
        
        public static string _ReplayGainMode {
            get {
                return ResourceManager.GetString("_ReplayGainMode", resourceCulture);
            }
        }
        
        public static string _ClippingPrevention {
            get {
                return ResourceManager.GetString("_ClippingPrevention", resourceCulture);
            }
        }
        
        public static string _Preamp {
            get {
                return ResourceManager.GetString("_Preamp", resourceCulture);
            }
        }
        
        public static string _ServerAddress {
            get {
                return ResourceManager.GetString("_ServerAddress", resourceCulture);
            }
        }
        
        public static string _Username {
            get {
                return ResourceManager.GetString("_Username", resourceCulture);
            }
        }
        
        public static string _PasswordOneWay {
            get {
                return ResourceManager.GetString("_PasswordOneWay", resourceCulture);
            }
        }
        
        public static string _IgnoreSslErrors {
            get {
                return ResourceManager.GetString("_IgnoreSslErrors", resourceCulture);
            }
        }
        
        public static string _ScrobbleToServer {
            get {
                return ResourceManager.GetString("_ScrobbleToServer", resourceCulture);
            }
        }
        
        public static string _ScrobbleMinimumPercentage {
            get {
                return ResourceManager.GetString("_ScrobbleMinimumPercentage", resourceCulture);
            }
        }
        
        public static string _ScrobbleMinimumSeconds {
            get {
                return ResourceManager.GetString("_ScrobbleMinimumSeconds", resourceCulture);
            }
        }
        
        public static string _SyncPlayQueue {
            get {
                return ResourceManager.GetString("_SyncPlayQueue", resourceCulture);
            }
        }
        
        public static string _ThemeSystem {
            get {
                return ResourceManager.GetString("_ThemeSystem", resourceCulture);
            }
        }
        
        public static string _ThemeLight {
            get {
                return ResourceManager.GetString("_ThemeLight", resourceCulture);
            }
        }
        
        public static string _ThemeDark {
            get {
                return ResourceManager.GetString("_ThemeDark", resourceCulture);
            }
        }
        
        public static string _ReplayGainModeNone {
            get {
                return ResourceManager.GetString("_ReplayGainModeNone", resourceCulture);
            }
        }
        
        public static string _ReplayGainModeAuto {
            get {
                return ResourceManager.GetString("_ReplayGainModeAuto", resourceCulture);
            }
        }
        
        public static string _ReplayGainModeAlbum {
            get {
                return ResourceManager.GetString("_ReplayGainModeAlbum", resourceCulture);
            }
        }
        
        public static string _ReplayGainModeTrack {
            get {
                return ResourceManager.GetString("_ReplayGainModeTrack", resourceCulture);
            }
        }
        
        public static string _ReplayGainClippingOff {
            get {
                return ResourceManager.GetString("_ReplayGainClippingOff", resourceCulture);
            }
        }
        
        public static string _ReplayGainClippingReduceGain {
            get {
                return ResourceManager.GetString("_ReplayGainClippingReduceGain", resourceCulture);
            }
        }
        
        public static string _LanguageEnglishGb {
            get {
                return ResourceManager.GetString("_LanguageEnglishGb", resourceCulture);
            }
        }
        
        public static string _LanguageEnglish {
            get {
                return ResourceManager.GetString("_LanguageEnglish", resourceCulture);
            }
        }
        
        public static string _SettingsValidationServerUri {
            get {
                return ResourceManager.GetString("_SettingsValidationServerUri", resourceCulture);
            }
        }
        
        public static string _SettingsValidationPreampRange {
            get {
                return ResourceManager.GetString("_SettingsValidationPreampRange", resourceCulture);
            }
        }
        
        public static string _SettingsValidationScrobblePercentRange {
            get {
                return ResourceManager.GetString("_SettingsValidationScrobblePercentRange", resourceCulture);
            }
        }
    }
}
