//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinSonic.Resources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinSonic.Resources.Localisation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string _Album {
            get {
                return ResourceManager.GetString("_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string _Albums {
            get {
                return ResourceManager.GetString("_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string _Artist {
            get {
                return ResourceManager.GetString("_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist(s).
        /// </summary>
        public static string _ArtistOptionalMultiple {
            get {
                return ResourceManager.GetString("_ArtistOptionalMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string _Artists {
            get {
                return ResourceManager.GetString("_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string _Back {
            get {
                return ResourceManager.GetString("_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string _Duration {
            get {
                return ResourceManager.GetString("_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started!.
        /// </summary>
        public static string _LandingGetStarted {
            get {
                return ResourceManager.GetString("_LandingGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to WinSonic!.
        /// </summary>
        public static string _LandingTitle {
            get {
                return ResourceManager.GetString("_LandingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets go!.
        /// </summary>
        public static string _LetsGo {
            get {
                return ResourceManager.GetString("_LetsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string _Next {
            get {
                return ResourceManager.GetString("_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string _Playlists {
            get {
                return ResourceManager.GetString("_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Configuration.
        /// </summary>
        public static string _ServerConfiguration {
            get {
                return ResourceManager.GetString("_ServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        public static string _ServerHostname {
            get {
                return ResourceManager.GetString("_ServerHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string _ServerPassword {
            get {
                return ResourceManager.GetString("_ServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string _ServerUsername {
            get {
                return ResourceManager.GetString("_ServerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string _Settings {
            get {
                return ResourceManager.GetString("_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve synced everything with the server and ready to play.
        /// </summary>
        public static string _SetupCompleteBody {
            get {
                return ResourceManager.GetString("_SetupCompleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Complete.
        /// </summary>
        public static string _SetupCompleteTitle {
            get {
                return ResourceManager.GetString("_SetupCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Connection and synchronising data with the server, please wait....
        /// </summary>
        public static string _SyncServerSubtitle {
            get {
                return ResourceManager.GetString("_SyncServerSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronising Server.
        /// </summary>
        public static string _SyncServerTitle {
            get {
                return ResourceManager.GetString("_SyncServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string _Title {
            get {
                return ResourceManager.GetString("_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string _Tracks {
            get {
                return ResourceManager.GetString("_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ahh.
        /// </summary>
        public static string _WinSonicAbout {
            get {
                return ResourceManager.GetString("_WinSonicAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An OpenSubsonic compatible media player for Windows..
        /// </summary>
        public static string _WinSonicSubtitle {
            get {
                return ResourceManager.GetString("_WinSonicSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinSonic.
        /// </summary>
        public static string _WinSonicTitle {
            get {
                return ResourceManager.GetString("_WinSonicTitle", resourceCulture);
            }
        }
    }
}
