<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WinSonic.Data.Sync\WinSonic.Data.Sync.csproj" />
      <ProjectReference Include="..\WinSonic.Gui.Misc.ImageTools\WinSonic.Gui.Misc.ImageTools.csproj" />
      <ProjectReference Include="..\WinSonic.Playback\WinSonic.Playback.csproj" />
      <ProjectReference Include="..\WinSonic.Player\WinSonic.Player.csproj" />
      <ProjectReference Include="..\WinSonic.Resources\WinSonic.Resources.csproj" />
      <ProjectReference Include="..\WinSonic.Service\WinSonic.Service.csproj" />
    </ItemGroup>

</Project>
