/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ArtistInfo2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArtistInfo2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArtistInfo2
        //private ArtistInfo2 instance;

        public ArtistInfo2Tests()
        {
            // TODO uncomment below to create an instance of ArtistInfo2
            //instance = new ArtistInfo2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArtistInfo2
        /// </summary>
        [Fact]
        public void ArtistInfo2InstanceTest()
        {
            // TODO uncomment below to test "IsType" ArtistInfo2
            //Assert.IsType<ArtistInfo2>(instance);
        }

        /// <summary>
        /// Test the property 'Biography'
        /// </summary>
        [Fact]
        public void BiographyTest()
        {
            // TODO unit test for the property 'Biography'
        }

        /// <summary>
        /// Test the property 'MusicBrainzId'
        /// </summary>
        [Fact]
        public void MusicBrainzIdTest()
        {
            // TODO unit test for the property 'MusicBrainzId'
        }

        /// <summary>
        /// Test the property 'LastFmUrl'
        /// </summary>
        [Fact]
        public void LastFmUrlTest()
        {
            // TODO unit test for the property 'LastFmUrl'
        }

        /// <summary>
        /// Test the property 'SmallImageUrl'
        /// </summary>
        [Fact]
        public void SmallImageUrlTest()
        {
            // TODO unit test for the property 'SmallImageUrl'
        }

        /// <summary>
        /// Test the property 'MediumImageUrl'
        /// </summary>
        [Fact]
        public void MediumImageUrlTest()
        {
            // TODO unit test for the property 'MediumImageUrl'
        }

        /// <summary>
        /// Test the property 'LargeImageUrl'
        /// </summary>
        [Fact]
        public void LargeImageUrlTest()
        {
            // TODO unit test for the property 'LargeImageUrl'
        }

        /// <summary>
        /// Test the property 'SimilarArtist'
        /// </summary>
        [Fact]
        public void SimilarArtistTest()
        {
            // TODO unit test for the property 'SimilarArtist'
        }
    }
}
