/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ArtistWithAlbumsID3
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArtistWithAlbumsID3Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArtistWithAlbumsID3
        //private ArtistWithAlbumsID3 instance;

        public ArtistWithAlbumsID3Tests()
        {
            // TODO uncomment below to create an instance of ArtistWithAlbumsID3
            //instance = new ArtistWithAlbumsID3();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArtistWithAlbumsID3
        /// </summary>
        [Fact]
        public void ArtistWithAlbumsID3InstanceTest()
        {
            // TODO uncomment below to test "IsType" ArtistWithAlbumsID3
            //Assert.IsType<ArtistWithAlbumsID3>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'CoverArt'
        /// </summary>
        [Fact]
        public void CoverArtTest()
        {
            // TODO unit test for the property 'CoverArt'
        }

        /// <summary>
        /// Test the property 'ArtistImageUrl'
        /// </summary>
        [Fact]
        public void ArtistImageUrlTest()
        {
            // TODO unit test for the property 'ArtistImageUrl'
        }

        /// <summary>
        /// Test the property 'AlbumCount'
        /// </summary>
        [Fact]
        public void AlbumCountTest()
        {
            // TODO unit test for the property 'AlbumCount'
        }

        /// <summary>
        /// Test the property 'Starred'
        /// </summary>
        [Fact]
        public void StarredTest()
        {
            // TODO unit test for the property 'Starred'
        }

        /// <summary>
        /// Test the property 'MusicBrainzId'
        /// </summary>
        [Fact]
        public void MusicBrainzIdTest()
        {
            // TODO unit test for the property 'MusicBrainzId'
        }

        /// <summary>
        /// Test the property 'SortName'
        /// </summary>
        [Fact]
        public void SortNameTest()
        {
            // TODO unit test for the property 'SortName'
        }

        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

        /// <summary>
        /// Test the property 'Album'
        /// </summary>
        [Fact]
        public void AlbumTest()
        {
            // TODO unit test for the property 'Album'
        }
    }
}
