/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ArtistsID3
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArtistsID3Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArtistsID3
        //private ArtistsID3 instance;

        public ArtistsID3Tests()
        {
            // TODO uncomment below to create an instance of ArtistsID3
            //instance = new ArtistsID3();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArtistsID3
        /// </summary>
        [Fact]
        public void ArtistsID3InstanceTest()
        {
            // TODO uncomment below to test "IsType" ArtistsID3
            //Assert.IsType<ArtistsID3>(instance);
        }

        /// <summary>
        /// Test the property 'IgnoredArticles'
        /// </summary>
        [Fact]
        public void IgnoredArticlesTest()
        {
            // TODO unit test for the property 'IgnoredArticles'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
    }
}
