/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CodecProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CodecProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CodecProfile
        //private CodecProfile instance;

        public CodecProfileTests()
        {
            // TODO uncomment below to create an instance of CodecProfile
            //instance = new CodecProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CodecProfile
        /// </summary>
        [Fact]
        public void CodecProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" CodecProfile
            //Assert.IsType<CodecProfile>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Limitations'
        /// </summary>
        [Fact]
        public void LimitationsTest()
        {
            // TODO unit test for the property 'Limitations'
        }
    }
}
