/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Contributor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContributorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Contributor
        //private Contributor instance;

        public ContributorTests()
        {
            // TODO uncomment below to create an instance of Contributor
            //instance = new Contributor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Contributor
        /// </summary>
        [Fact]
        public void ContributorInstanceTest()
        {
            // TODO uncomment below to test "IsType" Contributor
            //Assert.IsType<Contributor>(instance);
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }

        /// <summary>
        /// Test the property 'SubRole'
        /// </summary>
        [Fact]
        public void SubRoleTest()
        {
            // TODO unit test for the property 'SubRole'
        }

        /// <summary>
        /// Test the property 'Artist'
        /// </summary>
        [Fact]
        public void ArtistTest()
        {
            // TODO unit test for the property 'Artist'
        }
    }
}
