/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Cue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Cue
        //private Cue instance;

        public CueTests()
        {
            // TODO uncomment below to create an instance of Cue
            //instance = new Cue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Cue
        /// </summary>
        [Fact]
        public void CueInstanceTest()
        {
            // TODO uncomment below to test "IsType" Cue
            //Assert.IsType<Cue>(instance);
        }

        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }

        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }

        /// <summary>
        /// Test the property 'ByteStart'
        /// </summary>
        [Fact]
        public void ByteStartTest()
        {
            // TODO unit test for the property 'ByteStart'
        }

        /// <summary>
        /// Test the property 'ByteEnd'
        /// </summary>
        [Fact]
        public void ByteEndTest()
        {
            // TODO unit test for the property 'ByteEnd'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
