/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetArtistInfoResponseSubsonicResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetArtistInfoResponseSubsonicResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetArtistInfoResponseSubsonicResponse
        //private GetArtistInfoResponseSubsonicResponse instance;

        public GetArtistInfoResponseSubsonicResponseTests()
        {
            // TODO uncomment below to create an instance of GetArtistInfoResponseSubsonicResponse
            //instance = new GetArtistInfoResponseSubsonicResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetArtistInfoResponseSubsonicResponse
        /// </summary>
        [Fact]
        public void GetArtistInfoResponseSubsonicResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetArtistInfoResponseSubsonicResponse
            //Assert.IsType<GetArtistInfoResponseSubsonicResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ServerVersion'
        /// </summary>
        [Fact]
        public void ServerVersionTest()
        {
            // TODO unit test for the property 'ServerVersion'
        }

        /// <summary>
        /// Test the property 'OpenSubsonic'
        /// </summary>
        [Fact]
        public void OpenSubsonicTest()
        {
            // TODO unit test for the property 'OpenSubsonic'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'ArtistInfo'
        /// </summary>
        [Fact]
        public void ArtistInfoTest()
        {
            // TODO unit test for the property 'ArtistInfo'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
