/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetLyricsBySongIdResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetLyricsBySongIdResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetLyricsBySongIdResponse
        //private GetLyricsBySongIdResponse instance;

        public GetLyricsBySongIdResponseTests()
        {
            // TODO uncomment below to create an instance of GetLyricsBySongIdResponse
            //instance = new GetLyricsBySongIdResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetLyricsBySongIdResponse
        /// </summary>
        [Fact]
        public void GetLyricsBySongIdResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetLyricsBySongIdResponse
            //Assert.IsType<GetLyricsBySongIdResponse>(instance);
        }

        /// <summary>
        /// Test the property 'SubsonicResponse'
        /// </summary>
        [Fact]
        public void SubsonicResponseTest()
        {
            // TODO unit test for the property 'SubsonicResponse'
        }
    }
}
