/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetLyricsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetLyricsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetLyricsResponse
        //private GetLyricsResponse instance;

        public GetLyricsResponseTests()
        {
            // TODO uncomment below to create an instance of GetLyricsResponse
            //instance = new GetLyricsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetLyricsResponse
        /// </summary>
        [Fact]
        public void GetLyricsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetLyricsResponse
            //Assert.IsType<GetLyricsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'SubsonicResponse'
        /// </summary>
        [Fact]
        public void SubsonicResponseTest()
        {
            // TODO unit test for the property 'SubsonicResponse'
        }
    }
}
