/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetRandomSongsSuccessResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetRandomSongsSuccessResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetRandomSongsSuccessResponse
        //private GetRandomSongsSuccessResponse instance;

        public GetRandomSongsSuccessResponseTests()
        {
            // TODO uncomment below to create an instance of GetRandomSongsSuccessResponse
            //instance = new GetRandomSongsSuccessResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetRandomSongsSuccessResponse
        /// </summary>
        [Fact]
        public void GetRandomSongsSuccessResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetRandomSongsSuccessResponse
            //Assert.IsType<GetRandomSongsSuccessResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ServerVersion'
        /// </summary>
        [Fact]
        public void ServerVersionTest()
        {
            // TODO unit test for the property 'ServerVersion'
        }

        /// <summary>
        /// Test the property 'OpenSubsonic'
        /// </summary>
        [Fact]
        public void OpenSubsonicTest()
        {
            // TODO unit test for the property 'OpenSubsonic'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'RandomSongs'
        /// </summary>
        [Fact]
        public void RandomSongsTest()
        {
            // TODO unit test for the property 'RandomSongs'
        }
    }
}
