/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetSongsByGenreSuccessResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSongsByGenreSuccessResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSongsByGenreSuccessResponse
        //private GetSongsByGenreSuccessResponse instance;

        public GetSongsByGenreSuccessResponseTests()
        {
            // TODO uncomment below to create an instance of GetSongsByGenreSuccessResponse
            //instance = new GetSongsByGenreSuccessResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSongsByGenreSuccessResponse
        /// </summary>
        [Fact]
        public void GetSongsByGenreSuccessResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSongsByGenreSuccessResponse
            //Assert.IsType<GetSongsByGenreSuccessResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ServerVersion'
        /// </summary>
        [Fact]
        public void ServerVersionTest()
        {
            // TODO unit test for the property 'ServerVersion'
        }

        /// <summary>
        /// Test the property 'OpenSubsonic'
        /// </summary>
        [Fact]
        public void OpenSubsonicTest()
        {
            // TODO unit test for the property 'OpenSubsonic'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'SongsByGenre'
        /// </summary>
        [Fact]
        public void SongsByGenreTest()
        {
            // TODO unit test for the property 'SongsByGenre'
        }
    }
}
