/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetSimilarSongs2SuccessResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSimilarSongs2SuccessResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSimilarSongs2SuccessResponse
        //private GetSimilarSongs2SuccessResponse instance;

        public GetSimilarSongs2SuccessResponseTests()
        {
            // TODO uncomment below to create an instance of GetSimilarSongs2SuccessResponse
            //instance = new GetSimilarSongs2SuccessResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSimilarSongs2SuccessResponse
        /// </summary>
        [Fact]
        public void GetSimilarSongs2SuccessResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSimilarSongs2SuccessResponse
            //Assert.IsType<GetSimilarSongs2SuccessResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ServerVersion'
        /// </summary>
        [Fact]
        public void ServerVersionTest()
        {
            // TODO unit test for the property 'ServerVersion'
        }

        /// <summary>
        /// Test the property 'OpenSubsonic'
        /// </summary>
        [Fact]
        public void OpenSubsonicTest()
        {
            // TODO unit test for the property 'OpenSubsonic'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'SimilarSongs2'
        /// </summary>
        [Fact]
        public void SimilarSongs2Test()
        {
            // TODO unit test for the property 'SimilarSongs2'
        }
    }
}
