/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetTokenInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetTokenInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetTokenInfoResponse
        //private GetTokenInfoResponse instance;

        public GetTokenInfoResponseTests()
        {
            // TODO uncomment below to create an instance of GetTokenInfoResponse
            //instance = new GetTokenInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetTokenInfoResponse
        /// </summary>
        [Fact]
        public void GetTokenInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetTokenInfoResponse
            //Assert.IsType<GetTokenInfoResponse>(instance);
        }

        /// <summary>
        /// Test the property 'SubsonicResponse'
        /// </summary>
        [Fact]
        public void SubsonicResponseTest()
        {
            // TODO unit test for the property 'SubsonicResponse'
        }
    }
}
