/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Indexes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IndexesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Indexes
        //private Indexes instance;

        public IndexesTests()
        {
            // TODO uncomment below to create an instance of Indexes
            //instance = new Indexes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Indexes
        /// </summary>
        [Fact]
        public void IndexesInstanceTest()
        {
            // TODO uncomment below to test "IsType" Indexes
            //Assert.IsType<Indexes>(instance);
        }

        /// <summary>
        /// Test the property 'IgnoredArticles'
        /// </summary>
        [Fact]
        public void IgnoredArticlesTest()
        {
            // TODO unit test for the property 'IgnoredArticles'
        }

        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Fact]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }

        /// <summary>
        /// Test the property 'Shortcut'
        /// </summary>
        [Fact]
        public void ShortcutTest()
        {
            // TODO unit test for the property 'Shortcut'
        }

        /// <summary>
        /// Test the property 'Child'
        /// </summary>
        [Fact]
        public void ChildTest()
        {
            // TODO unit test for the property 'Child'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
    }
}
