/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing InternetRadioStation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InternetRadioStationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InternetRadioStation
        //private InternetRadioStation instance;

        public InternetRadioStationTests()
        {
            // TODO uncomment below to create an instance of InternetRadioStation
            //instance = new InternetRadioStation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InternetRadioStation
        /// </summary>
        [Fact]
        public void InternetRadioStationInstanceTest()
        {
            // TODO uncomment below to test "IsType" InternetRadioStation
            //Assert.IsType<InternetRadioStation>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'StreamUrl'
        /// </summary>
        [Fact]
        public void StreamUrlTest()
        {
            // TODO unit test for the property 'StreamUrl'
        }

        /// <summary>
        /// Test the property 'HomePageUrl'
        /// </summary>
        [Fact]
        public void HomePageUrlTest()
        {
            // TODO unit test for the property 'HomePageUrl'
        }

        /// <summary>
        /// Test the property 'CoverArt'
        /// </summary>
        [Fact]
        public void CoverArtTest()
        {
            // TODO unit test for the property 'CoverArt'
        }
    }
}
