/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Playlist
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlaylistTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Playlist
        //private Playlist instance;

        public PlaylistTests()
        {
            // TODO uncomment below to create an instance of Playlist
            //instance = new Playlist();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Playlist
        /// </summary>
        [Fact]
        public void PlaylistInstanceTest()
        {
            // TODO uncomment below to test "IsType" Playlist
            //Assert.IsType<Playlist>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

        /// <summary>
        /// Test the property 'Public'
        /// </summary>
        [Fact]
        public void PublicTest()
        {
            // TODO unit test for the property 'Public'
        }

        /// <summary>
        /// Test the property 'SongCount'
        /// </summary>
        [Fact]
        public void SongCountTest()
        {
            // TODO unit test for the property 'SongCount'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Changed'
        /// </summary>
        [Fact]
        public void ChangedTest()
        {
            // TODO unit test for the property 'Changed'
        }

        /// <summary>
        /// Test the property 'CoverArt'
        /// </summary>
        [Fact]
        public void CoverArtTest()
        {
            // TODO unit test for the property 'CoverArt'
        }

        /// <summary>
        /// Test the property 'AllowedUser'
        /// </summary>
        [Fact]
        public void AllowedUserTest()
        {
            // TODO unit test for the property 'AllowedUser'
        }

        /// <summary>
        /// Test the property 'Readonly'
        /// </summary>
        [Fact]
        public void ReadonlyTest()
        {
            // TODO unit test for the property 'Readonly'
        }

        /// <summary>
        /// Test the property 'ValidUntil'
        /// </summary>
        [Fact]
        public void ValidUntilTest()
        {
            // TODO unit test for the property 'ValidUntil'
        }
    }
}
