/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ReplayGain
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReplayGainTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReplayGain
        //private ReplayGain instance;

        public ReplayGainTests()
        {
            // TODO uncomment below to create an instance of ReplayGain
            //instance = new ReplayGain();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReplayGain
        /// </summary>
        [Fact]
        public void ReplayGainInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReplayGain
            //Assert.IsType<ReplayGain>(instance);
        }

        /// <summary>
        /// Test the property 'TrackGain'
        /// </summary>
        [Fact]
        public void TrackGainTest()
        {
            // TODO unit test for the property 'TrackGain'
        }

        /// <summary>
        /// Test the property 'AlbumGain'
        /// </summary>
        [Fact]
        public void AlbumGainTest()
        {
            // TODO unit test for the property 'AlbumGain'
        }

        /// <summary>
        /// Test the property 'TrackPeak'
        /// </summary>
        [Fact]
        public void TrackPeakTest()
        {
            // TODO unit test for the property 'TrackPeak'
        }

        /// <summary>
        /// Test the property 'AlbumPeak'
        /// </summary>
        [Fact]
        public void AlbumPeakTest()
        {
            // TODO unit test for the property 'AlbumPeak'
        }

        /// <summary>
        /// Test the property 'BaseGain'
        /// </summary>
        [Fact]
        public void BaseGainTest()
        {
            // TODO unit test for the property 'BaseGain'
        }

        /// <summary>
        /// Test the property 'FallbackGain'
        /// </summary>
        [Fact]
        public void FallbackGainTest()
        {
            // TODO unit test for the property 'FallbackGain'
        }
    }
}
