/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ScanStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScanStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScanStatus
        //private ScanStatus instance;

        public ScanStatusTests()
        {
            // TODO uncomment below to create an instance of ScanStatus
            //instance = new ScanStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScanStatus
        /// </summary>
        [Fact]
        public void ScanStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScanStatus
            //Assert.IsType<ScanStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Scanning'
        /// </summary>
        [Fact]
        public void ScanningTest()
        {
            // TODO unit test for the property 'Scanning'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
    }
}
