/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResult2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResult2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResult2
        //private SearchResult2 instance;

        public SearchResult2Tests()
        {
            // TODO uncomment below to create an instance of SearchResult2
            //instance = new SearchResult2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResult2
        /// </summary>
        [Fact]
        public void SearchResult2InstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResult2
            //Assert.IsType<SearchResult2>(instance);
        }

        /// <summary>
        /// Test the property 'Artist'
        /// </summary>
        [Fact]
        public void ArtistTest()
        {
            // TODO unit test for the property 'Artist'
        }

        /// <summary>
        /// Test the property 'Album'
        /// </summary>
        [Fact]
        public void AlbumTest()
        {
            // TODO unit test for the property 'Album'
        }

        /// <summary>
        /// Test the property 'Song'
        /// </summary>
        [Fact]
        public void SongTest()
        {
            // TODO unit test for the property 'Song'
        }
    }
}
