/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SimilarSongs2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimilarSongs2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SimilarSongs2
        //private SimilarSongs2 instance;

        public SimilarSongs2Tests()
        {
            // TODO uncomment below to create an instance of SimilarSongs2
            //instance = new SimilarSongs2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimilarSongs2
        /// </summary>
        [Fact]
        public void SimilarSongs2InstanceTest()
        {
            // TODO uncomment below to test "IsType" SimilarSongs2
            //Assert.IsType<SimilarSongs2>(instance);
        }

        /// <summary>
        /// Test the property 'Song'
        /// </summary>
        [Fact]
        public void SongTest()
        {
            // TODO unit test for the property 'Song'
        }
    }
}
