/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubsonicResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubsonicResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubsonicResponse
        //private SubsonicResponse instance;

        public SubsonicResponseTests()
        {
            // TODO uncomment below to create an instance of SubsonicResponse
            //instance = new SubsonicResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubsonicResponse
        /// </summary>
        [Fact]
        public void SubsonicResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubsonicResponse
            //Assert.IsType<SubsonicResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VarSubsonicResponse'
        /// </summary>
        [Fact]
        public void VarSubsonicResponseTest()
        {
            // TODO unit test for the property 'VarSubsonicResponse'
        }
    }
}
