/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubsonicError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubsonicErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubsonicError
        //private SubsonicError instance;

        public SubsonicErrorTests()
        {
            // TODO uncomment below to create an instance of SubsonicError
            //instance = new SubsonicError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubsonicError
        /// </summary>
        [Fact]
        public void SubsonicErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubsonicError
            //Assert.IsType<SubsonicError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'HelpUrl'
        /// </summary>
        [Fact]
        public void HelpUrlTest()
        {
            // TODO unit test for the property 'HelpUrl'
        }
    }
}
