/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Transcoding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TranscodingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Transcoding
        //private Transcoding instance;

        public TranscodingTests()
        {
            // TODO uncomment below to create an instance of Transcoding
            //instance = new Transcoding();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Transcoding
        /// </summary>
        [Fact]
        public void TranscodingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Transcoding
            //Assert.IsType<Transcoding>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Endpoints'
        /// </summary>
        [Fact]
        public void EndpointsTest()
        {
            // TODO unit test for the property 'Endpoints'
        }
    }
}
