/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TranscodeDecision
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TranscodeDecisionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TranscodeDecision
        //private TranscodeDecision instance;

        public TranscodeDecisionTests()
        {
            // TODO uncomment below to create an instance of TranscodeDecision
            //instance = new TranscodeDecision();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TranscodeDecision
        /// </summary>
        [Fact]
        public void TranscodeDecisionInstanceTest()
        {
            // TODO uncomment below to test "IsType" TranscodeDecision
            //Assert.IsType<TranscodeDecision>(instance);
        }

        /// <summary>
        /// Test the property 'CanDirectPlay'
        /// </summary>
        [Fact]
        public void CanDirectPlayTest()
        {
            // TODO unit test for the property 'CanDirectPlay'
        }

        /// <summary>
        /// Test the property 'CanTranscode'
        /// </summary>
        [Fact]
        public void CanTranscodeTest()
        {
            // TODO unit test for the property 'CanTranscode'
        }

        /// <summary>
        /// Test the property 'TranscodeReason'
        /// </summary>
        [Fact]
        public void TranscodeReasonTest()
        {
            // TODO unit test for the property 'TranscodeReason'
        }

        /// <summary>
        /// Test the property 'ErrorReason'
        /// </summary>
        [Fact]
        public void ErrorReasonTest()
        {
            // TODO unit test for the property 'ErrorReason'
        }

        /// <summary>
        /// Test the property 'TranscodeParams'
        /// </summary>
        [Fact]
        public void TranscodeParamsTest()
        {
            // TODO unit test for the property 'TranscodeParams'
        }

        /// <summary>
        /// Test the property 'SourceStream'
        /// </summary>
        [Fact]
        public void SourceStreamTest()
        {
            // TODO unit test for the property 'SourceStream'
        }

        /// <summary>
        /// Test the property 'TranscodeStream'
        /// </summary>
        [Fact]
        public void TranscodeStreamTest()
        {
            // TODO unit test for the property 'TranscodeStream'
        }
    }
}
