/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WinSonic.Subsonic.Client.Model;
using WinSonic.Subsonic.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WinSonic.Subsonic.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Work
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Work
        //private Work instance;

        public WorkTests()
        {
            // TODO uncomment below to create an instance of Work
            //instance = new Work();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Work
        /// </summary>
        [Fact]
        public void WorkInstanceTest()
        {
            // TODO uncomment below to test "IsType" Work
            //Assert.IsType<Work>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'MusicBrainzId'
        /// </summary>
        [Fact]
        public void MusicBrainzIdTest()
        {
            // TODO unit test for the property 'MusicBrainzId'
        }
    }
}
